// ============================================================
// DONNÉES HELDONICA — Destination Markers
// Source : données terrain Heldonica 2026
// ============================================================

export interface DestinationMarker {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  country: string;
  region: string;
  category: string;
  latitude: number;
  longitude: number;
  link: string;
  image: string;
}

export const destinationsData: DestinationMarker[] = [
  {
    id: 'madere',
    slug: 'madere',
    title: 'Madère',
    excerpt: 'Île portugaise de l\'Atlantique. Levadas, falaises, villages suspendus entre l\'ocean et les nuages.',
    country: 'Portugal',
    region: 'Europe',
    category: 'ile',
    latitude: 32.6669,
    longitude: -16.9241,
    link: '/destinations/madere',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'zurich',
    slug: 'zurich',
    title: 'Zurich',
    excerpt: 'Badi flottantes, brasseries artisanales et vieille ville dense. La ville où l\'eau change le tempo.',
    country: 'Suisse',
    region: 'Europe',
    category: 'ville',
    latitude: 47.3769,
    longitude: 8.5417,
    link: '/destinations/zurich',
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&q=80',
  },
  {
    id: 'suisse',
    slug: 'suisse',
    title: 'Suisse',
    excerpt: 'Montagnes, lacs, trains impeccables. La Suisse devient juste quand on cesse de la résumer à son prix.',
    country: 'Suisse',
    region: 'Europe',
    category: 'montagne',
    latitude: 46.8182,
    longitude: 8.2275,
    link: '/destinations/suisse',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
  },
  {
    id: 'roumanie',
    slug: 'roumanie',
    title: 'Roumanie',
    excerpt: 'Timișoara, Delta du Danube, Carpates. Le terrain de l\'enfance et des villages qui n\'ont pas laissé tomber leur rythme.',
    country: 'Roumanie',
    region: 'Europe',
    category: 'culture',
    latitude: 45.9432,
    longitude: 24.9668,
    link: '/destinations/roumanie',
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
  },
  {
    id: 'timisoara',
    slug: 'timisoara',
    title: 'Timișoara',
    excerpt: 'Ville hongroise autrichienne. Art Nouveau, jardins et vibe européenne. 2h30 de Paris.',
    country: 'Roumanie',
    region: 'Europe',
    category: 'ville',
    latitude: 45.7489,
    longitude: 21.2087,
    link: '/destinations/timisoara',
    image: 'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=800&q=80',
  },
  {
    id: 'sicile',
    slug: 'sicile',
    title: 'Sicile',
    excerpt: 'Île méditerranéenne. Etna, temples grecs, villages de pêcheurs et la meilleure cuisine d\'Italie.',
    country: 'Italie',
    region: 'Europe',
    category: 'ile',
    latitude: 37.5999,
    longitude: 14.0154,
    link: '/destinations/sicile',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80',
  },
  {
    id: 'sardaigne',
    slug: 'sardaigne',
    title: 'Sardaigne',
    excerpt: 'Entre Méditerranée et mer Tyrrhénienne. Les plages les plus belles d\'Europe et les montagnes du centre.',
    country: 'Italie',
    region: 'Europe',
    category: 'ile',
    latitude: 40.1209,
    longitude: 9.0129,
    link: '/destinations/sardaigne',
    image: 'https://images.unsplash.com/photo-1548796706-4e1a5a4c9f0c?w=800&q=80',
  },
  {
    id: 'cagliari',
    slug: 'cagliari',
    title: 'Cagliari',
    excerpt: 'Le sud de la Sardaigne. Capitale, lagune aux flamants roses, vieille ville castello.',
    country: 'Italie',
    region: 'Europe',
    category: 'ville',
    latitude: 39.2238,
    longitude: 9.1217,
    link: '/destinations/sardaigne/cagliari',
    image: 'https://images.unsplash.com/photo-1548796706-4e1a5a4c9f0c?w=800&q=80',
  },
  {
    id: 'paris',
    slug: 'paris',
    title: 'Paris',
    excerpt: 'Île-de-France slow travel. Paris alternatif, Petite Ceinture, canaux, streets art et quartiers vivants.',
    country: 'France',
    region: 'Europe',
    category: 'ville',
    latitude: 48.8566,
    longitude: 2.3522,
    link: '/destinations/idf/paris',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
  },
  {
    id: 'versailles',
    slug: 'versailles',
    title: 'Versailles',
    excerpt: 'Château et jardins. Le domaine que les客车 de tourisme évitent de regarder vraiment.',
    country: 'France',
    region: 'Europe',
    category: 'culture',
    latitude: 48.8014,
    longitude: 2.1301,
    link: '/destinations/idf/versailles',
    image: 'https://images.unsplash.com/photo-1564594736624-def7a10ab047?w=800&q=80',
  },
  {
    id: 'giverny',
    slug: 'giverny',
    title: 'Giverny',
    excerpt: 'Jardins de Monet. Nymphéas, pont japonais et la lumière qui change tout en mai.',
    country: 'France',
    region: 'Europe',
    category: 'nature',
    latitude: 49.0705,
    longitude: 1.5286,
    link: '/destinations/idf/giverny',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
  },
  {
    id: 'fontainebleau',
    slug: 'fontainebleau',
    title: 'Fontainebleau',
    excerpt: 'Forêt, sable blanc et blocs de grès. L\'escalade et la rando à 1h de Paris.',
    country: 'France',
    region: 'Europe',
    category: 'nature',
    latitude: 48.4021,
    longitude: 2.7045,
    link: '/destinations/idf/fontainebleau',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
  },
  {
    id: 'normandie',
    slug: 'normandie',
    title: 'Normandie',
    excerpt: 'Falaises de craie, ports de pêche, bocage du Pays d\'Auge. Le Havre UNESCO, Honfleur, Etretat.',
    country: 'France',
    region: 'Europe',
    category: 'cote',
    latitude: 49.1829,
    longitude: 0.3707,
    link: '/destinations/normandie',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
  },
  {
    id: 'le-havre',
    slug: 'le-havre',
    title: 'Le Havre',
    excerpt: 'Deuxième port de France, patrimoine UNESCO d\'Auguste Perret. Une ville qui surprend quand on prend le temps.',
    country: 'France',
    region: 'Europe',
    category: 'ville',
    latitude: 49.4944,
    longitude: 0.1079,
    link: '/destinations/normandie/le-havre',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
  },
  {
    id: 'lisbonne',
    slug: 'lisbonne',
    title: 'Lisbonne',
    excerpt: 'Collines, Tram 28, fado et les açasï de Santa Catarina. La ville qui respire par lesвелича.',
    country: 'Portugal',
    region: 'Europe',
    category: 'ville',
    latitude: 38.7223,
    longitude: -9.1393,
    link: '/destinations/portugal/lisbonne',
    image: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&q=80',
  },
  {
    id: 'porto',
    slug: 'porto',
    title: 'Porto',
    excerpt: 'Vin de Porto, architecture, bord du Douro. La ville qui se goûte en marchant.',
    country: 'Portugal',
    region: 'Europe',
    category: 'ville',
    latitude: 41.1579,
    longitude: -8.6291,
    link: '/destinations/portugal/porto',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
  },
  {
    id: 'colombie',
    slug: 'colombie',
    title: 'Colombie',
    excerpt: 'Bogota, Medellin, Cartago et la chaleur de l\'Amérique du Sud. Le voyage qui repousse les contours.',
    country: 'Colombie',
    region: 'Amérique latine',
    category: 'culture',
    latitude: 4.5709,
    longitude: -74.2973,
    link: '/destinations/colombie',
    image: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=800&q=80',
  },
  {
    id: 'bogota',
    slug: 'bogota',
    title: 'Bogota',
    excerpt: 'Capitale andine à 2600m. Street art, districts créatifs et la chaleur humaine qui compense l\'altitude.',
    country: 'Colombie',
    region: 'Amérique latine',
    category: 'ville',
    latitude: 4.7110,
    longitude: -74.0721,
    link: '/destinations/colombie/bogota',
    image: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=800&q=80',
  },
  {
    id: 'medellin',
    slug: 'medellin',
    title: 'Medellin',
    excerpt: 'Ville de l\'éternel printemps. Communes, métro cable et la transformation la plus impressionnante d\'Amérique latine.',
    country: 'Colombie',
    region: 'Amérique latine',
    category: 'ville',
    latitude: 6.2442,
    longitude: -75.5812,
    link: '/destinations/colombie/medellin',
    image: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=800&q=80',
  },
  {
    id: 'brasov',
    slug: 'brasov',
    title: 'Brasov',
    excerpt: 'Montagne, Dracula etPizza. Le centre médiéval que les客车 de Dracula rendent célèbre.',
    country: 'Roumanie',
    region: 'Europe',
    category: 'ville',
    latitude: 45.6427,
    longitude: 25.5888,
    link: '/destinations/roumanie/brasov',
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
  },
  {
    id: 'transylvanie',
    slug: 'transylvanie',
    title: 'Transylvanie',
    excerpt: 'Villages saxons, châteaux, légendes. La région que les récits ont rendue plus grande que son échelle réelle.',
    country: 'Roumanie',
    region: 'Europe',
    category: 'culture',
    latitude: 46.0,
    longitude: 24.5,
    link: '/destinations/roumanie/transylvanie',
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
  },
  {
    id: 'funchal',
    slug: 'funchal',
    title: 'Funchal',
    excerpt: 'Capitale de Madère. Marché, front de mer,缆车 et le pain chaud de 7h qui dit tout.',
    country: 'Portugal',
    region: 'Europe',
    category: 'ville',
    latitude: 32.6669,
    longitude: -16.9241,
    link: '/destinations/madere/funchal',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'porto-moniz',
    slug: 'porto-moniz',
    title: 'Porto Moniz',
    excerpt: 'Piscines volcaniques naturelles. Le nord-ouest de Madère où la lave a créé des bassins transparents.',
    country: 'Portugal',
    region: 'Europe',
    category: 'nature',
    latitude: 32.8669,
    longitude: -17.1669,
    link: '/destinations/madere/porto-moniz',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'sao-vicente',
    slug: 'sao-vicente',
    title: 'São Vicente',
    excerpt: 'Le nord oublié de Madère. Grottes volcaniques, plage noire et éoliennes dans la brume.',
    country: 'Portugal',
    region: 'Europe',
    category: 'nature',
    latitude: 32.7833,
    longitude: -17.0333,
    link: '/destinations/madere/sao-vicente',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'ponta-do-sol',
    slug: 'ponta-do-sol',
    title: 'Ponta do Sol',
    excerpt: 'Le sud de Madère. Plus intime, plus doux, idéal pour un voyage en duo orienté slow et coucher de soleil.',
    country: 'Portugal',
    region: 'Europe',
    category: 'cote',
    latitude: 32.65,
    longitude: -17.1,
    link: '/destinations/madere/ponta-do-sol',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'ribeiro-frio',
    slug: 'ribeiro-frio',
    title: 'Ribeiro Frio',
    excerpt: 'Forêt de laurisylve et levadas. Le point médian de Madère où les sources froides traversent la montagne.',
    country: 'Portugal',
    region: 'Europe',
    category: 'nature',
    latitude: 32.7167,
    longitude: -16.8833,
    link: '/destinations/madere/ribeiro-frio',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
  {
    id: 'cabo-girao',
    slug: 'cabo-girao',
    title: 'Cabo Girao',
    excerpt: 'La plus haute falaise d\'Europe. 580m à pic sur l\'Atlantique, une vue qui coupe le souffle.',
    country: 'Portugal',
    region: 'Europe',
    category: 'nature',
    latitude: 32.65,
    longitude: -17.0,
    link: '/destinations/madere/cabo-girao',
    image: 'https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=80',
  },
];

export default destinationsData;