-- ============================================================================
-- Page /travel-planning-form : contenu piloté par le CMS
-- Date: 2026-08-01 — généré par scripts/generate-travel-planning-form-cms.mjs
--
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('travel-planning-form', 'hero_title_1', 'text', 'Dis-nous où tu veux aller.', 'Titre hero — ligne 1', true),
  ('travel-planning-form', 'hero_title_2', 'text', 'On s''occupe du reste.', 'Titre hero — ligne 2', true),
  ('travel-planning-form', 'hero_description', 'textarea', 'Pas d''itinéraire copié-collé. Un voyage conçu sur mesure, à partir de ce que tu vis vraiment.', 'Description hero', true),
  ('travel-planning-form', 'hero_note', 'text', '2 min · Sans engagement · Réponse sous 48h', 'Note hero (2 min · Sans engagement…)', true),
  ('travel-planning-form', 'step_name_1', 'text', 'L''Inspiration', 'Nom étape 1', true),
  ('travel-planning-form', 'step_name_2', 'text', 'Ton Voyage', 'Nom étape 2', true),
  ('travel-planning-form', 'step_name_3', 'text', 'Tes Coordonnées', 'Nom étape 3', true),
  ('travel-planning-form', 'step_1_title', 'text', 'Étape 1 : L''Inspiration', 'Titre étape 1', true),
  ('travel-planning-form', 'step_2_title', 'text', 'Étape 2 : Ton Voyage', 'Titre étape 2', true),
  ('travel-planning-form', 'step_3_title', 'text', 'Étape 3 : Tes Coordonnées', 'Titre étape 3', true),
  ('travel-planning-form', 'q_trip_type', 'textarea', 'C''est quel type d''escapade ?', 'Question étape 1 — trip_type', true),
  ('travel-planning-form', 'q_vibe', 'textarea', 'Quelle est la vibe recherchée ?', 'Question étape 2 — vibe', true),
  ('travel-planning-form', 'q_destination', 'textarea', 'Tu as déjà une destination en tête ?', 'Question étape 3 — destination', true),
  ('travel-planning-form', 'q_duration', 'textarea', 'Quelle durée envisages-tu ?', 'Question étape 3 — duration', true),
  ('travel-planning-form', 'q_budget', 'textarea', 'Quel est ton budget global pour le voyage ?', 'Question étape 3 — budget', true),
  ('travel-planning-form', 'trip_1_label', 'textarea', 'Couple', 'trip 1 — libellé', true),
  ('travel-planning-form', 'trip_1_emoji', 'text', '💑', 'trip 1 — emoji', true),
  ('travel-planning-form', 'trip_2_label', 'textarea', 'Solo', 'trip 2 — libellé', true),
  ('travel-planning-form', 'trip_2_emoji', 'text', '🧭', 'trip 2 — emoji', true),
  ('travel-planning-form', 'trip_3_label', 'textarea', 'Amis', 'trip 3 — libellé', true),
  ('travel-planning-form', 'trip_3_emoji', 'text', '🥂', 'trip 3 — emoji', true),
  ('travel-planning-form', 'trip_4_label', 'textarea', 'Lune de miel', 'trip 4 — libellé', true),
  ('travel-planning-form', 'trip_4_emoji', 'text', '💍', 'trip 4 — emoji', true),
  ('travel-planning-form', 'trip_5_label', 'textarea', 'Famille', 'trip 5 — libellé', true),
  ('travel-planning-form', 'trip_5_emoji', 'text', '👨‍👩‍👧', 'trip 5 — emoji', true),
  ('travel-planning-form', 'trip_6_label', 'textarea', 'Autre', 'trip 6 — libellé', true),
  ('travel-planning-form', 'trip_6_emoji', 'text', '✨', 'trip 6 — emoji', true),
  ('travel-planning-form', 'vibe_1_label', 'textarea', 'Slow Travel & Détente', 'vibe 1 — libellé', true),
  ('travel-planning-form', 'vibe_1_emoji', 'text', '🌿', 'vibe 1 — emoji', true),
  ('travel-planning-form', 'vibe_2_label', 'textarea', 'Aventure & Nature', 'vibe 2 — libellé', true),
  ('travel-planning-form', 'vibe_2_emoji', 'text', '🏔️', 'vibe 2 — emoji', true),
  ('travel-planning-form', 'vibe_3_label', 'textarea', 'Culture & Gastronomie', 'vibe 3 — libellé', true),
  ('travel-planning-form', 'vibe_3_emoji', 'text', '🎭', 'vibe 3 — emoji', true),
  ('travel-planning-form', 'vibe_4_label', 'textarea', 'Éco-responsable & Durable', 'vibe 4 — libellé', true),
  ('travel-planning-form', 'vibe_4_emoji', 'text', '♻️', 'vibe 4 — emoji', true),
  ('travel-planning-form', 'vibe_5_label', 'textarea', 'Romantique & Intime', 'vibe 5 — libellé', true),
  ('travel-planning-form', 'vibe_5_emoji', 'text', '🕯️', 'vibe 5 — emoji', true),
  ('travel-planning-form', 'dest_1_label', 'textarea', 'Destination précise', 'dest 1 — libellé', true),
  ('travel-planning-form', 'dest_1_emoji', 'text', '📍', 'dest 1 — emoji', true),
  ('travel-planning-form', 'dest_2_label', 'textarea', 'Suggestions Heldonica', 'dest 2 — libellé', true),
  ('travel-planning-form', 'dest_2_emoji', 'text', '🗺️', 'dest 2 — emoji', true),
  ('travel-planning-form', 'dest_3_label', 'textarea', 'Région/continent', 'dest 3 — libellé', true),
  ('travel-planning-form', 'dest_3_emoji', 'text', '🌐', 'dest 3 — emoji', true),
  ('travel-planning-form', 'budget_1_label', 'textarea', 'Moins de 1 000 €', 'budget 1 — libellé', true),
  ('travel-planning-form', 'budget_1_emoji', 'text', '💛', 'budget 1 — emoji', true),
  ('travel-planning-form', 'budget_2_label', 'textarea', '1 000 – 2 500 €', 'budget 2 — libellé', true),
  ('travel-planning-form', 'budget_2_emoji', 'text', '💚', 'budget 2 — emoji', true),
  ('travel-planning-form', 'budget_3_label', 'textarea', '2 500 – 5 000 €', 'budget 3 — libellé', true),
  ('travel-planning-form', 'budget_3_emoji', 'text', '💙', 'budget 3 — emoji', true),
  ('travel-planning-form', 'budget_4_label', 'textarea', '5 000 € et +', 'budget 4 — libellé', true),
  ('travel-planning-form', 'budget_4_emoji', 'text', '💎', 'budget 4 — emoji', true),
  ('travel-planning-form', 'budget_5_label', 'textarea', 'Je préfère qu''on en discute', 'budget 5 — libellé', true),
  ('travel-planning-form', 'budget_5_emoji', 'text', '💬', 'budget 5 — emoji', true),
  ('travel-planning-form', 'duration_1_label', 'textarea', 'Week-end (2-3 jours)', 'Durée 1 — libellé', true),
  ('travel-planning-form', 'duration_2_label', 'textarea', 'Court séjour (4-6 jours)', 'Durée 2 — libellé', true),
  ('travel-planning-form', 'duration_3_label', 'textarea', '1 semaine', 'Durée 3 — libellé', true),
  ('travel-planning-form', 'duration_4_label', 'textarea', '2 semaines', 'Durée 4 — libellé', true),
  ('travel-planning-form', 'duration_5_label', 'textarea', '3 semaines et +', 'Durée 5 — libellé', true),
  ('travel-planning-form', 'duration_6_label', 'textarea', 'Pas encore décidé·e', 'Durée 6 — libellé', true),
  ('travel-planning-form', 'date_label', 'text', 'Date de départ envisagée (optionnel)', 'Label date de départ', true),
  ('travel-planning-form', 'date_hint', 'text', 'Laisse vide si les dates sont flexibles', 'Aide date de départ', true),
  ('travel-planning-form', 'fname_label', 'text', 'Ton prénom', 'Label prénom', true),
  ('travel-planning-form', 'email_label', 'text', 'Ton email', 'Label email', true),
  ('travel-planning-form', 'phone_label', 'text', 'Ton numéro (optionnel)', 'Label téléphone', true),
  ('travel-planning-form', 'msg_label', 'text', 'Un mot sur ton voyage de rêve ? (optionnel)', 'Label message', true),
  ('travel-planning-form', 'footnote', 'textarea', '* Champs obligatoires. Tes données ne sont jamais revendues et ne servent qu''à concevoir ton itinéraire.', 'Note champs obligatoires', true),
  ('travel-planning-form', 'nav_back', 'text', 'Retour', 'Bouton retour', true),
  ('travel-planning-form', 'nav_next', 'text', 'Suivant', 'Bouton suivant', true),
  ('travel-planning-form', 'nav_sending', 'text', 'Envoi en cours…', 'Bouton envoi en cours', true),
  ('travel-planning-form', 'nav_submit', 'text', 'Envoyer ma demande', 'Bouton envoyer', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
