-- ============================================================================
-- Pages pleines (FAQ) : contenu piloté par le CMS (cms_editable_zones)
-- Date: 2026-08-01 — généré par scripts/generate-faq-pages-cms.mjs
-- ============================================================================
-- Les pages idf / sardaigne / kotor passent du hardcodé à des zones
-- éditables. Les valeurs sont EXACTEMENT le contenu affiché jusqu'ici.
--
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

-- ─── destinations-sardaigne ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('destinations-sardaigne', 'hero_image', 'image', '/og-default.jpg', 'Image du hero', true),
  ('destinations-sardaigne', 'hero_title', 'text', 'Sardaigne', 'Titre du hero', true),
  ('destinations-sardaigne', 'hero_subtitle', 'text', 'l''île qui ne se livre pas d''un seul coup', 'Sous-titre du hero', true),
  ('destinations-sardaigne', 'hero_description', 'textarea', 'Entre Méditerranée et mer Tyrrhénienne, la Sardaigne cache ses meilleures cartes à l''intérieur des terres, loin des plages célèbres.', 'Description du hero', true),
  ('destinations-sardaigne', 'intro_1', 'textarea', 'La Sardaigne, c''est l''île qui reste. Pas dans le sens d''un souvenir vague — dans le sens d''un endroit qui s''installe et ne repart plus. Les plages du sud autour de Cagliari, les lagunes roses aux flamants, les dunes sauvages de Piscinas. Et puis l''intérieur : les villages de pierre, les fêtes bariolées, les pecorino vieux qu''on mange au couteau.', 'Introduction 1', true),
  ('destinations-sardaigne', 'intro_2', 'textarea', 'Ce qu''on préfère ? Les agriturismes de la Barbagia, où l''on mange ce que la famille a produit. Et les routes qui ne mènent nulle part — jusqu''à ce qu''elles mènent quelque part d''extraordinaire.', 'Introduction 2', true),
  ('destinations-sardaigne', 'zone_1_title', 'text', 'Cagliari', 'Zone 1 — titre', true),
  ('destinations-sardaigne', 'zone_1_desc', 'textarea', 'Le sud. Capitale animée, lagune aux flamants, dunes de Piscinas.', 'Zone 1 — description', true),
  ('destinations-sardaigne', 'zone_2_title', 'text', 'Alghero', 'Zone 2 — titre', true),
  ('destinations-sardaigne', 'zone_2_desc', 'textarea', 'Nord-ouest. Ville catalane aux remparts dorés, grotte de Neptune.', 'Zone 2 — description', true),
  ('destinations-sardaigne', 'zone_3_title', 'text', 'Nuoro & Barbagia', 'Zone 3 — titre', true),
  ('destinations-sardaigne', 'zone_3_desc', 'textarea', 'L''intérieur. Villages de pierre, agritourismes, cuisine de montagne.', 'Zone 3 — description', true),
  ('destinations-sardaigne', 'zone_4_title', 'text', 'Asinara', 'Zone 4 — titre', true),
  ('destinations-sardaigne', 'zone_4_desc', 'textarea', 'Île sauvage du nord-ouest. Parc national, ânes blancs, plongée.', 'Zone 4 — description', true),
  ('destinations-sardaigne', 'period_1', 'textarea', '✓ Mai – Juin : idéal, mer et terrasses', 'Meilleure période 1', true),
  ('destinations-sardaigne', 'period_2', 'textarea', '✓ Septembre : parfait, foules réduites', 'Meilleure période 2', true),
  ('destinations-sardaigne', 'period_3', 'textarea', '⚠ Juillet – Août : chaud, très fréquenté', 'Meilleure période 3', true),
  ('destinations-sardaigne', 'budget_1', 'textarea', 'Hébergement : 70–150€/nuit', 'Budget 1', true),
  ('destinations-sardaigne', 'budget_2', 'textarea', 'Repas au restaurant : 40–70€/jour', 'Budget 2', true),
  ('destinations-sardaigne', 'budget_3', 'textarea', 'Vol Paris–Cagliari : ~120–200€ A/R', 'Budget 3', true),
  ('destinations-sardaigne', 'faq_1_q', 'text', 'Quand aller en Sardaigne ?', 'FAQ 1 — question', true),
  ('destinations-sardaigne', 'faq_1_a', 'textarea', 'Mai-juin ou septembre : plages parfaites, foules réduites. Juillet-août reste possible mais très fréquenté.', 'FAQ 1 — réponse', true),
  ('destinations-sardaigne', 'faq_2_q', 'text', 'Où loger en Sardaigne ?', 'FAQ 2 — question', true),
  ('destinations-sardaigne', 'faq_2_a', 'textarea', 'Cagliari pour la culture et la vie locale, Alghero pour le charme catalan, et les agriturismes de l''intérieur pour le vrai slow travel.', 'FAQ 2 — réponse', true),
  ('destinations-sardaigne', 'faq_3_q', 'text', 'Comment se déplacer en Sardaigne ?', 'FAQ 3 — question', true),
  ('destinations-sardaigne', 'faq_3_a', 'textarea', 'La voiture est indispensable pour explorer les villages et l''intérieur. Vols directs vers Cagliari (CAG) ou Olbia (OLB) depuis Paris.', 'FAQ 3 — réponse', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();

-- ─── destinations-idf ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('destinations-idf', 'hero_image', 'image', '/og-default.jpg', 'Image du hero', true),
  ('destinations-idf', 'hero_badge', 'text', 'Destinations France', 'Badge du hero', true),
  ('destinations-idf', 'hero_title', 'text', 'Île-de-France', 'Titre du hero', true),
  ('destinations-idf', 'hero_description', 'textarea', 'On habite à côté, et Paris nous surprend encore. Pas le Paris des selfies devant la Tour Eiffel — l''autre Paris, celui de la Petite Ceinture, du Canal de l''Ourcq un dimanche matin, des cours intérieures cachées dans le Marais.', 'Description du hero', true),
  ('destinations-idf', 'intro_title', 'text', 'Le slow travel commence parfois à 30 minutes de chez soi', 'Titre de l''introduction', true),
  ('destinations-idf', 'intro_1', 'textarea', 'L''Île-de-France est la région la plus visitée du monde — et pourtant, on peut y passer une semaine entière sans croiser un touriste. La Petite Ceinture au 14e, les bords du Canal de l''Ourcq un mardi matin, la forêt de Fontainebleau en automne : c''est cette région-là qu''on documente.', 'Introduction 1', true),
  ('destinations-idf', 'intro_2', 'textarea', 'Pas les monuments (on les connaît), pas les photos Instagram (on les a vues) — les adresses de quartier, les promenades qui n''existent sur aucune carte de métro, les marchés où les locaux font vraiment leurs courses.', 'Introduction 2', true),
  ('destinations-idf', 'pepite_1_titre', 'text', 'La Petite Ceinture (14e)', 'Pépite 1 — titre', true),
  ('destinations-idf', 'pepite_1_desc', 'textarea', 'L''ancienne voie ferrée devenue promenade sauvage au cœur de Paris. Street art, végétation folle, silence improbable. Un Paris d''explorateur à 15 minutes du Sacré-Cœur.', 'Pépite 1 — description', true),
  ('destinations-idf', 'pepite_1_tag', 'text', 'Urbex légal', 'Pépite 1 — tag', true),
  ('destinations-idf', 'pepite_2_titre', 'text', 'Rue Mouffetard & Singh''Nature', 'Pépite 2 — titre', true),
  ('destinations-idf', 'pepite_2_desc', 'textarea', 'Le marché du jeudi matin, les fromagers, le boulanger de quartier. Le soir, une table végétarienne fusion au Singh''Nature — notre découverte la plus mémorable du 5e.', 'Pépite 2 — description', true),
  ('destinations-idf', 'pepite_2_tag', 'text', 'Food', 'Pépite 2 — tag', true),
  ('destinations-idf', 'pepite_3_titre', 'text', 'Canal de l''Ourcq à vélo', 'Pépite 3 — titre', true),
  ('destinations-idf', 'pepite_3_desc', 'textarea', 'De La Villette jusqu''à Meaux en longeant le canal. Une journée entière, sans voiture, en glissant entre les péniches et les écluses. Le slow travel commence à 30 minutes de chez soi.', 'Pépite 3 — description', true),
  ('destinations-idf', 'pepite_3_tag', 'text', 'Vélo', 'Pépite 3 — tag', true),
  ('destinations-idf', 'pepite_4_titre', 'text', 'Forêt de Fontainebleau', 'Pépite 4 — titre', true),
  ('destinations-idf', 'pepite_4_desc', 'textarea', 'Le château, oui — mais surtout la forêt. Escalade sur les blocs de grès, pique-nique en sous-bois, silence garanti hors week-end. 40 minutes depuis Paris-Gare de Lyon.', 'Pépite 4 — description', true),
  ('destinations-idf', 'pepite_4_tag', 'text', 'Nature', 'Pépite 4 — tag', true),
  ('destinations-idf', 'zone_1_label', 'text', 'Paris', 'Zone 1 — label', true),
  ('destinations-idf', 'zone_1_desc', 'textarea', 'La capitale autrement — Petite Ceinture, Mouffetard, Canal de l''Ourcq. La Paris des quartiers, pas des monuments.', 'Zone 1 — description', true),
  ('destinations-idf', 'zone_2_label', 'text', 'Versailles', 'Zone 2 — label', true),
  ('destinations-idf', 'zone_2_desc', 'textarea', 'Les jardins à l''aube avant les cars de touristes, le marché couvert, le quartier Saint-Louis pour déjeuner.', 'Zone 2 — description', true),
  ('destinations-idf', 'zone_3_label', 'text', 'Giverny', 'Zone 3 — label', true),
  ('destinations-idf', 'zone_3_desc', 'textarea', 'Les jardins de Monet en avril ou en juin — pas en août. Une demi-journée, une lumière douce, pas de foule.', 'Zone 3 — description', true),
  ('destinations-idf', 'zone_4_label', 'text', 'Fontainebleau', 'Zone 4 — label', true),
  ('destinations-idf', 'zone_4_desc', 'textarea', 'Forêt, blocs de grès, chemins marqués. La nature à 40 minutes de Paris — notre escape dominical préféré.', 'Zone 4 — description', true),
  ('destinations-idf', 'when_1', 'html', '<strong>Avril – Juin</strong> — idéal. Jardins en fleurs, température parfaite, files d''attente raisonnables.', 'Quand y aller 1', true),
  ('destinations-idf', 'when_2', 'html', '<strong>Septembre – Octobre</strong> — lumière dorée, foule réduite, terrasses encore ouvertes.', 'Quand y aller 2', true),
  ('destinations-idf', 'when_3', 'html', '<strong>Juillet – Août</strong> — possible mais chaud et fréquenté. Privilégier les parcs et les plans d''eau.', 'Quand y aller 3', true),
  ('destinations-idf', 'transport_1', 'html', '<strong>Pass Navigo zones 1-5</strong> — couvre tout : métro, RER, bus, trains vers Versailles et Fontainebleau.', 'Transport & budget 1', true),
  ('destinations-idf', 'transport_2', 'html', '<strong>Hébergement</strong> — 80–200€/nuit selon arrondissement. Le 11e, 18e et 20e restent les plus abordables.', 'Transport & budget 2', true),
  ('destinations-idf', 'transport_3', 'html', '<strong>Repas</strong> — compter 15–35€/personne dans un bistrot de quartier. Éviter les restaurants à menus photos.', 'Transport & budget 3', true),
  ('destinations-idf', 'faq_1_q', 'text', 'Quand aller à Paris et en Île-de-France ?', 'FAQ 1 — question', true),
  ('destinations-idf', 'faq_1_a', 'textarea', 'Avril à juin pour les jardins et la douceur, septembre-octobre pour les files d''attente réduites. Juillet-août reste agréable mais plus fréquenté et potentiellement caniculaire.', 'FAQ 1 — réponse', true),
  ('destinations-idf', 'faq_2_q', 'text', 'Comment se déplacer en Île-de-France sans voiture ?', 'FAQ 2 — question', true),
  ('destinations-idf', 'faq_2_a', 'textarea', 'Le Pass Navigo (zones 1-5) couvre métro, RER, bus, et trains vers Versailles, Fontainebleau et Giverny. Pour Paris intra-muros, le Vélib'' est idéal. La voiture est souvent un obstacle plus qu''une aide.', 'FAQ 2 — réponse', true),
  ('destinations-idf', 'faq_3_q', 'text', 'Que faire autour de Paris en journée ?', 'FAQ 3 — question', true),
  ('destinations-idf', 'faq_3_a', 'textarea', 'Fontainebleau (40 min, RER D) pour la forêt et l''escalade sur blocs. Versailles (35 min, RER C) pour les jardins plutôt que le château. Giverny (1h30 en train + bus) pour les jardins de Monet d''avril à novembre.', 'FAQ 3 — réponse', true),
  ('destinations-idf', 'faq_4_q', 'text', 'Y a-t-il des activités slow travel gratuites à Paris ?', 'FAQ 4 — question', true),
  ('destinations-idf', 'faq_4_a', 'textarea', 'Oui — la Petite Ceinture (14e, 15e), le Canal de l''Ourcq à vélo, les marchés de quartier (Mouffetard, Belleville), les jardins du Palais-Royal. Les musées nationaux sont gratuits le premier dimanche de chaque mois.', 'FAQ 4 — réponse', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();

-- ─── destinations-montenegro-kotor ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('destinations-montenegro-kotor', 'hero_image', 'image', '/og-default.jpg', 'Image du hero', true),
  ('destinations-montenegro-kotor', 'hero_badge', 'text', 'Monténégro · Bouches de Kotor', 'Badge du hero', true),
  ('destinations-montenegro-kotor', 'hero_title', 'text', 'Kotor avant les croisiéristes', 'Titre du hero', true),
  ('destinations-montenegro-kotor', 'hero_description', 'textarea', 'Le secret de Kotor, c''est l''heure. À 7h du matin, la vieille ville est à toi. Les ruelles pavées, la lumière sur la baie, le silence avant l''invasion. Voici comment on l''a vécue — et comment tu peux la vivre aussi.', 'Description du hero', true),
  ('destinations-montenegro-kotor', 'intro_title', 'text', 'La baie de Kotor au lever du soleil', 'Titre de l''introduction', true),
  ('destinations-montenegro-kotor', 'intro_1', 'html', ' <strong>6h30.</strong> On a quitté notre hébergement dans la vieille ville avant l''aube. Les premières lueurs sont apparues à l''horizon, rougissant les peaks calcaires. La baie était mate, sans un pli. Quelques pêcheurs préparaient leurs bateaux. ', 'Introduction 1', true),
  ('destinations-montenegro-kotor', 'intro_2', 'html', ' C''est à ce moment précis que Kotor révèle ce qu''il est vraiment : une ville magnifique coincée entre montagne et mer, qui mérite mieux que les groupes de croisiéristes qui la envahissent à partir de 10h. ', 'Introduction 2', true),
  ('destinations-montenegro-kotor', 'intro_3', 'html', ' <strong>Notre conseil terrain :</strong> Lève-toi à 7h. Fais les remparts avant 9h. Ensuite, va nager dans une crique de la baie ou prends le bateau pour Perast. ', 'Introduction 3', true),
  ('destinations-montenegro-kotor', 'why_1_title', 'text', 'Une vieille ville vide', 'Pourquoi 1 — titre', true),
  ('destinations-montenegro-kotor', 'why_1_desc', 'textarea', 'Avant 9h, les ruelles pavées sont à toi. Les portes colorées, les chats endormis, l''odeur du café qui sort des fenêtres — c''est le Kotor authentique.', 'Pourquoi 1 — description', true),
  ('destinations-montenegro-kotor', 'why_2_title', 'text', 'Des remparts tranquilles', 'Pourquoi 2 — titre', true),
  ('destinations-montenegro-kotor', 'why_2_desc', 'textarea', '1350 marches avec vue sur la baie — difficile de profiter si tu montes derrière 200 passagers de cruise. À 7h, tu seras seul·e ou quasi.', 'Pourquoi 2 — description', true),
  ('destinations-montenegro-kotor', 'why_3_title', 'text', 'La lumière du matin', 'Pourquoi 3 — titre', true),
  ('destinations-montenegro-kotor', 'why_3_desc', 'textarea', 'Le soleil levant sur les falaises de la baie est un spectacle. C''est le moment pour les photos — sans filtres, sans monde.', 'Pourquoi 3 — description', true),
  ('destinations-montenegro-kotor', 'why_4_title', 'text', 'Les criques accessibles', 'Pourquoi 4 — titre', true),
  ('destinations-montenegro-kotor', 'why_4_desc', 'textarea', 'Les petites plages autour de Kotor sont vides le matin. Bajova Quay, Stoliv — tu auras le choix.', 'Pourquoi 4 — description', true),
  ('destinations-montenegro-kotor', 'day_1_time', 'text', '7h', 'Journée type 1 — heure', true),
  ('destinations-montenegro-kotor', 'day_1_title', 'text', 'Lever du soleil sur la baie', 'Journée type 1 — titre', true),
  ('destinations-montenegro-kotor', 'day_1_desc', 'textarea', 'Promenade le long de la marina, puis remontée vers les remparts. Si tu montes, prépare de l''eau — les marches sont raides.', 'Journée type 1 — description', true),
  ('destinations-montenegro-kotor', 'day_2_time', 'text', '9h', 'Journée type 2 — heure', true),
  ('destinations-montenegro-kotor', 'day_2_title', 'text', 'Petit-déjeuner dans la vieille ville', 'Journée type 2 — titre', true),
  ('destinations-montenegro-kotor', 'day_2_desc', 'textarea', 'Premier café, dernier calme. Profites-en pour flâner dans les ruelles avant que les boutiques ouvrent.', 'Journée type 2 — description', true),
  ('destinations-montenegro-kotor', 'day_3_time', 'text', '10h', 'Journée type 3 — heure', true),
  ('destinations-montenegro-kotor', 'day_3_title', 'text', 'Direction le port pour l''excursion', 'Journée type 3 — titre', true),
  ('destinations-montenegro-kotor', 'day_3_desc', 'textarea', 'Les bateaux partent du vieux port. Destination : les bouches de Kotor, Perast, et l''île de Notre-Dame-du-Rocher. <strong className="text-mahogany"> Astuce : négociez directement avec les pêcheurs sur le port.</strong>', 'Journée type 3 — description', true),
  ('destinations-montenegro-kotor', 'day_4_time', 'text', '15h', 'Journée type 4 — heure', true),
  ('destinations-montenegro-kotor', 'day_4_title', 'text', 'Pause plage ou balade douce', 'Journée type 4 — titre', true),
  ('destinations-montenegro-kotor', 'day_4_desc', 'textarea', 'L''après-midi, Kotor est envahi. C''est le moment pour une crique au bord de la baie ou une expédition vers la réserve naturelle de Lustica.', 'Journée type 4 — description', true),
  ('destinations-montenegro-kotor', 'info_1_title', 'text', 'Quand y aller', 'Info 1 — titre', true),
  ('destinations-montenegro-kotor', 'info_1_item_1', 'html', '<strong className="text-eucalyptus">Mai-juin :</strong> Températures agréables, peu de croisiéristes', 'Info 1 — item 1', true),
  ('destinations-montenegro-kotor', 'info_1_item_2', 'html', '<strong className="text-eucalyptus">Septembre-octobre :</strong> Mer chaude, touristes en baisse', 'Info 1 — item 2', true),
  ('destinations-montenegro-kotor', 'info_1_item_3', 'html', '<strong className="text-red-500">Juillet-août :</strong> À éviter si tu cherches le calme', 'Info 1 — item 3', true),
  ('destinations-montenegro-kotor', 'info_2_title', 'text', 'Combien de temps', 'Info 2 — titre', true),
  ('destinations-montenegro-kotor', 'info_2_item_1', 'html', '<strong className="text-eucalyptus">2-3 jours :</strong> Vieille ville, remparts, Perast', 'Info 2 — item 1', true),
  ('destinations-montenegro-kotor', 'info_2_item_2', 'html', '<strong className="text-eucalyptus">4-5 jours :</strong> Ajout de Lovćen ou Budva', 'Info 2 — item 2', true),
  ('destinations-montenegro-kotor', 'info_2_item_3', 'html', '<strong className="text-eucalyptus">1 semaine+ :</strong> Durée complète pour le Monténégro', 'Info 2 — item 3', true),
  ('destinations-montenegro-kotor', 'info_3_title', 'text', 'Budget couple / jour', 'Info 3 — titre', true),
  ('destinations-montenegro-kotor', 'info_3_item_1', 'html', '<strong className="text-eucalyptus">Entrée remparts :</strong> ~15€/pers', 'Info 3 — item 1', true),
  ('destinations-montenegro-kotor', 'info_3_item_2', 'html', '<strong className="text-eucalyptus">Excursion bateau :</strong> ~40-60€/pers', 'Info 3 — item 2', true),
  ('destinations-montenegro-kotor', 'info_3_item_3', 'html', '<strong className="text-eucalyptus">Repas :</strong> ~20-30€/pers', 'Info 3 — item 3', true),
  ('destinations-montenegro-kotor', 'info_4_title', 'text', 'Pour qui', 'Info 4 — titre', true),
  ('destinations-montenegro-kotor', 'info_4_item_1', 'html', '<strong className="text-eucalyptus">Couples :</strong> Idéal pour un week-end romantique', 'Info 4 — item 1', true),
  ('destinations-montenegro-kotor', 'info_4_item_2', 'html', '<strong className="text-eucalyptus">Amis :</strong> Authentique, pas trop tourist', 'Info 4 — item 2', true),
  ('destinations-montenegro-kotor', 'info_4_item_3', 'html', '<strong className="text-eucalyptus">Familles :</strong> Facile avec enfants (pas de grosses marches)', 'Info 4 — item 3', true),
  ('destinations-montenegro-kotor', 'faq_1_q', 'text', 'Quel est le meilleur moment pour visiter Kotor ?', 'FAQ 1 — question', true),
  ('destinations-montenegro-kotor', 'faq_1_a', 'textarea', 'Tôt le matin (7h-9h) pour avoir la vieille ville avant l''arrivée des croisiéristes. Mai-juin et septembre-octobre offrent le meilleur équilibre température/affluence.', 'FAQ 1 — réponse', true),
  ('destinations-montenegro-kotor', 'faq_2_q', 'text', 'Combien de temps rester à Kotor ?', 'FAQ 2 — question', true),
  ('destinations-montenegro-kotor', 'faq_2_a', 'textarea', '2 à 3 jours suffisent pour découvrir la vieille ville, les remparts et une excursion dans les bouches de Kotor. Compte 4-5 jours si tu veux explorer Lovćen ou le Durmitor.', 'FAQ 2 — réponse', true),
  ('destinations-montenegro-kotor', 'faq_3_q', 'text', 'Les remparts de Kotor sont-ils difficiles ?', 'FAQ 3 — question', true),
  ('destinations-montenegro-kotor', 'faq_3_a', 'textarea', 'Oui — 1350 marches pour rejoindre la forteresse de San Giovanni. C''est éprouvant mais la vue sur la baie en vaut la peine. Partez tôt pour éviter la chaleur.', 'FAQ 3 — réponse', true),
  ('destinations-montenegro-kotor', 'verdict_who', 'textarea', 'Couples qui cherchent une destination romantique avec de vrais beaux paysages. Amateurs d''histoire (vieille ville UNESCO) et de nature (baie, montagnes).', 'Verdict — pour qui', true),
  ('destinations-montenegro-kotor', 'verdict_adore_1', 'textarea', '✓ La baie au lever du soleil', 'Verdict — on adore 1', true),
  ('destinations-montenegro-kotor', 'verdict_adore_2', 'textarea', '✓ Les ruelles pavées avant 9h', 'Verdict — on adore 2', true),
  ('destinations-montenegro-kotor', 'verdict_adore_3', 'textarea', '✓ L''excursion en bateau vers Perast', 'Verdict — on adore 3', true),
  ('destinations-montenegro-kotor', 'verdict_adore_4', 'textarea', '✓ Le rapport qualité-prix', 'Verdict — on adore 4', true),
  ('destinations-montenegro-kotor', 'verdict_avoid', 'textarea', 'Les croisiéristes. Juillet-août si tu cherches du slow travel. Les restaurants hors de la vieille ville — moins authentiques, plus chers.', 'Verdict — ce qu''on évite', true),
  ('destinations-montenegro-kotor', 'verdict_quote', 'textarea', '"Kotor se découvre à l''aube. Le reste de la journée, partez en bateau."', 'Verdict — citation', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();

-- ─── destinations-timisoara ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('destinations-timisoara', 'hero_image', 'image', '/og-default.jpg', 'Image du hero', true),
  ('destinations-timisoara', 'hero_badge', 'text', 'Roumanie · Banat', 'Badge du hero', true),
  ('destinations-timisoara', 'hero_title', 'text', 'Timișoara', 'Titre du hero', true),
  ('destinations-timisoara', 'hero_description', 'textarea', 'Première ville d''Europe à avoir eu l''éclairage électrique. Première ville de la révolution roumaine. Capitale européenne de la culture 2023. Et pourtant, presque personne ne s''y arrête.', 'Description du hero', true),
  ('destinations-timisoara', 'intro_title', 'text', 'La ville qu''on n''avait pas prévu d''aimer', 'Titre de l''introduction', true),
  ('destinations-timisoara', 'intro_1', 'textarea', 'On est arrivés à Timișoara par hasard, en route vers Bucarest. On est restés quatre jours. La ville a cette qualité rare : elle ne se donne pas d''emblée. Il faut traîner dans le Fabric le soir, s''asseoir sur la place Unirii avec un café, tourner dans les ruelles du vieux centre.', 'Introduction 1', true),
  ('destinations-timisoara', 'intro_2', 'textarea', 'Timișoara est roumaine, mais elle parle hongrois, serbe et allemand dans la même phrase. C''est une ville de carrefour, d''influences mêlées, d''histoire dense. Et depuis 2023, capitale européenne de la culture qui a investi dans ses scènes alternatives sans perdre son âme de quartier.', 'Introduction 2', true),
  ('destinations-timisoara', 'pepite_1_icon', 'text', '🏛️', 'Pépite 1 — icône', true),
  ('destinations-timisoara', 'pepite_1_tag', 'text', 'Incontournable', 'Pépite 1 — tag', true),
  ('destinations-timisoara', 'pepite_1_title', 'text', 'Piața Unirii', 'Pépite 1 — titre', true),
  ('destinations-timisoara', 'pepite_1_desc', 'textarea', 'La plus belle place baroque de Roumanie. Cathédrale catholique, fontaine, terrasses qui invitent à rester. Le matin, avant les touristes.', 'Pépite 1 — description', true),
  ('destinations-timisoara', 'pepite_2_icon', 'text', '🎨', 'Pépite 2 — icône', true),
  ('destinations-timisoara', 'pepite_2_tag', 'text', 'Pépite cachée', 'Pépite 2 — tag', true),
  ('destinations-timisoara', 'pepite_2_title', 'text', 'Cuib d''Arte', 'Pépite 2 — titre', true),
  ('destinations-timisoara', 'pepite_2_desc', 'textarea', 'Cour intérieure cachée dans le quartier Fabric. Galeries d''art, installations éphémères, café avec jardin. L''âme créative de la ville.', 'Pépite 2 — description', true),
  ('destinations-timisoara', 'pepite_3_icon', 'text', '🏚️', 'Pépite 3 — icône', true),
  ('destinations-timisoara', 'pepite_3_tag', 'text', 'Quartier', 'Pépite 3 — tag', true),
  ('destinations-timisoara', 'pepite_3_title', 'text', 'Quartier Fabric', 'Pépite 3 — titre', true),
  ('destinations-timisoara', 'pepite_3_desc', 'textarea', 'L''ancien quartier ouvrier en pleine renaissance. Street art, petits bars indépendants, ateliers d''artisans. L''endroit où la ville se réinvente.', 'Pépite 3 — description', true),
  ('destinations-timisoara', 'pepite_4_icon', 'text', '🇷🇴', 'Pépite 4 — icône', true),
  ('destinations-timisoara', 'pepite_4_tag', 'text', 'Histoire', 'Pépite 4 — tag', true),
  ('destinations-timisoara', 'pepite_4_title', 'text', 'Piața Victoriei', 'Pépite 4 — titre', true),
  ('destinations-timisoara', 'pepite_4_desc', 'textarea', 'Point de départ de la révolution roumaine de 1989. Opéra, cathédrale orthodoxe et cette longue avenue qui invite à la promenade du soir.', 'Pépite 4 — description', true),
  ('destinations-timisoara', 'pepite_5_icon', 'text', '🌳', 'Pépite 5 — icône', true),
  ('destinations-timisoara', 'pepite_5_tag', 'text', 'Nature urbaine', 'Pépite 5 — tag', true),
  ('destinations-timisoara', 'pepite_5_title', 'text', 'Parcul Civic', 'Pépite 5 — titre', true),
  ('destinations-timisoara', 'pepite_5_desc', 'textarea', 'Le poumon vert de la ville. Lac, barques, familles le dimanche. Les Timișoreni viennent ici pour ne rien faire — et ça se voit.', 'Pépite 5 — description', true),
  ('destinations-timisoara', 'pepite_6_icon', 'text', '🍸', 'Pépite 6 — icône', true),
  ('destinations-timisoara', 'pepite_6_tag', 'text', 'Vie locale', 'Pépite 6 — tag', true),
  ('destinations-timisoara', 'pepite_6_title', 'text', 'Strada Mercy & Piața Traian', 'Pépite 6 — titre', true),
  ('destinations-timisoara', 'pepite_6_desc', 'textarea', 'Artère Art Nouveau du vieux Fabric. Façades colorées en cours de restauration, cafés de spécialité, bars à cocktails abordables.', 'Pépite 6 — description', true),
  ('destinations-timisoara', 'sleep_1', 'html', '<strong>Hôtel Timișoara</strong> — Centre historique, vue Piața Victoriei. 70–100€/nuit.', 'Où dormir 1', true),
  ('destinations-timisoara', 'sleep_2', 'html', '<strong>Casa del Arte</strong> — Boutique hôtel dans une villa Art Nouveau restaurée. 60–90€.', 'Où dormir 2', true),
  ('destinations-timisoara', 'sleep_3', 'html', '<strong>Appartements Fabric</strong> — Location courte durée dans le quartier créatif. 40–60€.', 'Où dormir 3', true),
  ('destinations-timisoara', 'eat_1', 'html', '<strong>Conviva</strong> — Gastro-pub, cuisine locale revisitée. Réservation conseillée.', 'Où manger 1', true),
  ('destinations-timisoara', 'eat_2', 'html', '<strong>Barista Fabric</strong> — Café de spécialité, viennoiseries. Le matin incontournable.', 'Où manger 2', true),
  ('destinations-timisoara', 'eat_3', 'html', '<strong>Marchés du samedi</strong> — Piața Badea Cârțan. Fromages, charcuteries locales, légumes.', 'Où manger 3', true),
  ('destinations-timisoara', 'faq_1_q', 'text', 'Quand aller à Timișoara ?', 'FAQ 1 — question', true),
  ('destinations-timisoara', 'faq_1_a', 'textarea', 'Mai-juin pour les parcs en fleurs et les températures douces. Septembre-octobre pour les festivals de rue. Éviter juillet-août (chaleur intense, +35°C). Décembre pour le marché de Noël place Unirii.', 'FAQ 1 — réponse', true),
  ('destinations-timisoara', 'faq_2_q', 'text', 'Comment aller à Timișoara depuis Paris ?', 'FAQ 2 — question', true),
  ('destinations-timisoara', 'faq_2_a', 'textarea', 'Vol direct Paris-Timișoara avec Tarom (3h). Alternativement Paris-Bucarest puis train de nuit (6h) ou Budapest puis train (3h). Le trajet Budapest-Timișoara en train longe la frontière hongroise et est magnifique.', 'FAQ 2 — réponse', true),
  ('destinations-timisoara', 'faq_3_q', 'text', 'Quel budget pour Timișoara ?', 'FAQ 3 — question', true),
  ('destinations-timisoara', 'faq_3_a', 'textarea', 'La ville est très abordable : dîner dans un bon restaurant local entre 15-25€/pers, café 1,5-2€, hébergement 40-80€/nuit en hôtel centre-ville. Budget total : 70-100€/pers/jour confort inclus.', 'FAQ 3 — réponse', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
