-- ============================================================================
-- Page /quiz : contenu piloté par le CMS
-- Date: 2026-08-01 — généré par scripts/generate-quiz-cms.mjs
--
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('quiz', 'hero_badge', 'text', 'Quiz Heldonica', 'Badge du hero', true),
  ('quiz', 'hero_title', 'text', 'Quel voyageur es-tu ?', 'Titre du hero', true),
  ('quiz', 'hero_description', 'textarea', '5 questions pour découvrir ton profil travel et recevoir des recommandations personnalisées.', 'Description du hero', true),
  ('quiz', 'question_1', 'textarea', 'Comment tu choisis ta destination ?', 'Question 1', true),
  ('quiz', 'question_1_opt_1_emoji', 'text', '🏔️', 'Question 1 — option 1 emoji', true),
  ('quiz', 'question_1_opt_1_label', 'textarea', 'Tu cherches l''aventure, les émotions fortes et la nature sauvage', 'Question 1 — option 1', true),
  ('quiz', 'question_1_opt_2_emoji', 'text', '🏛️', 'Question 1 — option 2 emoji', true),
  ('quiz', 'question_1_opt_2_label', 'textarea', 'Histoire, art, architecture et rencontres locales', 'Question 1 — option 2', true),
  ('quiz', 'question_1_opt_3_emoji', 'text', '🌿', 'Question 1 — option 3 emoji', true),
  ('quiz', 'question_1_opt_3_label', 'textarea', 'Calme, paysages, déconnexion totale', 'Question 1 — option 3', true),
  ('quiz', 'question_1_opt_4_emoji', 'text', '🧘', 'Question 1 — option 4 emoji', true),
  ('quiz', 'question_1_opt_4_label', 'textarea', 'Tu veux te faire dorloter, spa, yoga, douceur', 'Question 1 — option 4', true),
  ('quiz', 'question_2', 'textarea', 'Ton rythme idéal en voyage ?', 'Question 2', true),
  ('quiz', 'question_2_opt_1_emoji', 'text', '⏰', 'Question 2 — option 1 emoji', true),
  ('quiz', 'question_2_opt_1_label', 'textarea', 'Tu te lèves à l''aube pour maximiser chaque journée', 'Question 2 — option 1', true),
  ('quiz', 'question_2_opt_2_emoji', 'text', '🚶', 'Question 2 — option 2 emoji', true),
  ('quiz', 'question_2_opt_2_label', 'textarea', '2-3 activités par jour, avec du temps pour flâner', 'Question 2 — option 2', true),
  ('quiz', 'question_2_opt_3_emoji', 'text', '🐢', 'Question 2 — option 3 emoji', true),
  ('quiz', 'question_2_opt_3_label', 'textarea', 'Lent, contemplatif, un seul lieu par jour', 'Question 2 — option 3', true),
  ('quiz', 'question_2_opt_4_emoji', 'text', '☀️', 'Question 2 — option 4 emoji', true),
  ('quiz', 'question_2_opt_4_label', 'textarea', 'Au rythme du soleil et de mes envies', 'Question 2 — option 4', true),
  ('quiz', 'question_3', 'textarea', 'Ton approche de l''hébergement ?', 'Question 3', true),
  ('quiz', 'question_3_opt_1_emoji', 'text', '🏕️', 'Question 3 — option 1 emoji', true),
  ('quiz', 'question_3_opt_1_label', 'textarea', 'Pragmatique : dortoirs, guesthouse, chez l''habitant', 'Question 3 — option 1', true),
  ('quiz', 'question_3_opt_2_emoji', 'text', '🏰', 'Question 3 — option 2 emoji', true),
  ('quiz', 'question_3_opt_2_label', 'textarea', 'Hôtel de caractère avec histoire, quartier authentique', 'Question 3 — option 2', true),
  ('quiz', 'question_3_opt_3_emoji', 'text', '🏡', 'Question 3 — option 3 emoji', true),
  ('quiz', 'question_3_opt_3_label', 'textarea', 'Éco-lodge, cabane, yourte ou maison isolée', 'Question 3 — option 3', true),
  ('quiz', 'question_3_opt_4_emoji', 'text', '🛁', 'Question 3 — option 4 emoji', true),
  ('quiz', 'question_3_opt_4_label', 'textarea', 'Spa, piscine, vue panoramique, confort total', 'Question 3 — option 4', true),
  ('quiz', 'question_4', 'textarea', 'Qu''est-ce qui te fait vibrer en voyage ?', 'Question 4', true),
  ('quiz', 'question_4_opt_1_emoji', 'text', '🎯', 'Question 4 — option 1 emoji', true),
  ('quiz', 'question_4_opt_1_label', 'textarea', 'Le sommet atteint, le trek réussi, l''adrénaline', 'Question 4 — option 1', true),
  ('quiz', 'question_4_opt_2_emoji', 'text', '💬', 'Question 4 — option 2 emoji', true),
  ('quiz', 'question_4_opt_2_label', 'textarea', 'Le marché local, le petit resto caché, la discussion avec un artisan', 'Question 4 — option 2', true),
  ('quiz', 'question_4_opt_3_emoji', 'text', '✨', 'Question 4 — option 3 emoji', true),
  ('quiz', 'question_4_opt_3_label', 'textarea', 'Le silence d''une forêt, le bruit des vagues, une aurore boréale', 'Question 4 — option 3', true),
  ('quiz', 'question_4_opt_4_emoji', 'text', '🌅', 'Question 4 — option 4 emoji', true),
  ('quiz', 'question_4_opt_4_label', 'textarea', 'Un massage, un coucher de soleil parfait, le repos profond', 'Question 4 — option 4', true),
  ('quiz', 'question_5', 'textarea', 'Ta philosophie de voyage en une phrase ?', 'Question 5', true),
  ('quiz', 'question_5_opt_1_emoji', 'text', '📖', 'Question 5 — option 1 emoji', true),
  ('quiz', 'question_5_opt_1_label', 'textarea', '"Vivre des histoires à raconter toute ma vie"', 'Question 5 — option 1', true),
  ('quiz', 'question_5_opt_2_emoji', 'text', '🌍', 'Question 5 — option 2 emoji', true),
  ('quiz', 'question_5_opt_2_label', 'textarea', '"Comprendre le monde à travers ceux qui y vivent"', 'Question 5 — option 2', true),
  ('quiz', 'question_5_opt_3_emoji', 'text', '🍃', 'Question 5 — option 3 emoji', true),
  ('quiz', 'question_5_opt_3_label', 'textarea', '"Retourner à l''essentiel, loin du bruit du monde"', 'Question 5 — option 3', true),
  ('quiz', 'question_5_opt_4_emoji', 'text', '💝', 'Question 5 — option 4 emoji', true),
  ('quiz', 'question_5_opt_4_label', 'textarea', '"Prendre soin de soi, c''est aussi voyager autrement"', 'Question 5 — option 4', true),
  ('quiz', 'profile_aventure_title', 'text', 'L''Aventurier', 'Profil aventure — titre', true),
  ('quiz', 'profile_aventure_description', 'textarea', 'Tu kiffes l''adrénaline, les défis et les paysages qui font tourner la tête. Tu veux des trips qui te marquent, pas des vacances lambda.', 'Profil aventure — description', true),
  ('quiz', 'profile_aventure_vibe_1', 'text', 'Trek', 'Profil aventure — vibe 1', true),
  ('quiz', 'profile_aventure_vibe_2', 'text', 'Randonnée', 'Profil aventure — vibe 2', true),
  ('quiz', 'profile_aventure_vibe_3', 'text', 'Nature intense', 'Profil aventure — vibe 3', true),
  ('quiz', 'profile_culture_title', 'text', 'Le Curieux Culturel', 'Profil culture — titre', true),
  ('quiz', 'profile_culture_description', 'textarea', 'Chaque voyage est une découverte. Tu veux comprendre les gens, l''histoire, les traditions. Un bon resto local te rend plus heureux qu''un spa.', 'Profil culture — description', true),
  ('quiz', 'profile_culture_vibe_1', 'text', 'Gastronomie', 'Profil culture — vibe 1', true),
  ('quiz', 'profile_culture_vibe_2', 'text', 'Patrimoine', 'Profil culture — vibe 2', true),
  ('quiz', 'profile_culture_vibe_3', 'text', 'Artisanat local', 'Profil culture — vibe 3', true),
  ('quiz', 'profile_nature_title', 'text', 'Le Slow Traveler', 'Profil nature — titre', true),
  ('quiz', 'profile_nature_description', 'textarea', 'Tu voyages pour te ressourcer. Un lieu, une atmosphère, du temps. Pas besoin de tout voir — tu veux vivre le lieu.', 'Profil nature — description', true),
  ('quiz', 'profile_nature_vibe_1', 'text', 'Éco-responsable', 'Profil nature — vibe 1', true),
  ('quiz', 'profile_nature_vibe_2', 'text', 'Bord de mer', 'Profil nature — vibe 2', true),
  ('quiz', 'profile_nature_vibe_3', 'text', 'Forêt', 'Profil nature — vibe 3', true),
  ('quiz', 'profile_bien-etre_title', 'text', 'L''Amateur de Bien-être', 'Profil bien-etre — titre', true),
  ('quiz', 'profile_bien-etre_description', 'textarea', 'Voyager pour se faire du bien. Tu mérites le meilleur, et tu le sais. Un voyage qui nourrit le corps et l''esprit.', 'Profil bien-etre — description', true),
  ('quiz', 'profile_bien-etre_vibe_1', 'text', 'Spa', 'Profil bien-etre — vibe 1', true),
  ('quiz', 'profile_bien-etre_vibe_2', 'text', 'Yoga', 'Profil bien-etre — vibe 2', true),
  ('quiz', 'profile_bien-etre_vibe_3', 'text', 'Gastronomie healthy', 'Profil bien-etre — vibe 3', true),
  ('quiz', 'result_badge', 'text', 'Ton profil voyage', 'Badge du résultat (Ton profil voyage)', true),
  ('quiz', 'result_destinations_title', 'text', 'Destinations recommandées', 'Titre bloc destinations recommandées', true),
  ('quiz', 'result_cta', 'text', 'Créer mon voyage sur mesure', 'CTA résultat (créer mon voyage)', true),
  ('quiz', 'result_retry', 'text', 'Refaire le quiz', 'Bouton refaire le quiz', true),
  ('quiz', 'trust_text', 'textarea', '+500 voyageurs accompagnés par an · Réponse sous 48h · 100% sur mesure', 'Ligne de confiance (pied de page)', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
