-- ===========================================================================
-- SEO metadata piloté par le CMS : title / description / og:image par page
-- Généré par scripts/cms-seo-metadata.mjs — valeurs initiales = fallbacks du code
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('a-propos', 'seo_title', 'text', 'À propos | Heldonica', 'SEO — title', true),
  ('a-propos', 'seo_description', 'textarea', 'Le duo derrière Heldonica. Notre histoire, notre philosophie du slow travel et pourquoi on conçoit des voyages sur mesure.', 'SEO — description', true),
  ('a-propos', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('contact', 'seo_title', 'text', 'Contact | Heldonica', 'SEO — title', true),
  ('contact', 'seo_description', 'textarea', 'Une question, un projet de voyage ? On est là. Écris-nous pour ton travel planning sur mesure ou toute autre demande.', 'SEO — description', true),
  ('contact', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-alentejo', 'seo_title', 'text', 'Alentejo : Guide Slow Travel Complet | Heldonica', 'SEO — title', true),
  ('destinations-alentejo', 'seo_description', 'textarea', 'Guide pilier Alentejo : quand partir, où dormir, vignobles, villages de pierre et itinéraire slow. 2 séjours vécus par le duo Heldonica.', 'SEO — description', true),
  ('destinations-alentejo', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-carte', 'seo_title', 'text', 'Carte des Destinations | Heldonica', 'SEO — title', true),
  ('destinations-carte', 'seo_description', 'textarea', 'Carte interactive de nos destinations slow travel : Madère, Sicile, Roumanie, Portugal et plus. Clique sur les marqueurs pour découvrir chaque pépite.', 'SEO — description', true),
  ('destinations-carte', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-colombie-bogota', 'seo_title', 'text', 'Bogota en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-colombie-bogota', 'seo_description', 'textarea', 'Capitale. 2600m, Graffiti, Candelaria en Colombie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-colombie-bogota', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-colombie-cali', 'seo_title', 'text', 'Cali en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-colombie-cali', 'seo_description', 'textarea', 'Capitale de la salsa. Valle del Cauca en Colombie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-colombie-cali', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-colombie-cartago', 'seo_title', 'text', 'Cartago en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-colombie-cartago', 'seo_description', 'textarea', 'Valle del Cauca. Zone cafe. Tradition en Colombie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-colombie-cartago', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-colombie-medellin', 'seo_title', 'text', 'Medellin en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-colombie-medellin', 'seo_description', 'textarea', 'Ville de l''éternel printemps. Parche, metro en Colombie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-colombie-medellin', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-colombie', 'seo_title', 'text', 'Colombie slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-colombie', 'seo_description', 'textarea', 'Guide slow travel Colombie : Bogotá, Medellín, Cali et la région du café. Adresses dénichées, itinéraires testés et conseils terrain par Heldonica.', 'SEO — description', true),
  ('destinations-colombie', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-compare', 'seo_title', 'text', 'Comparer les destinations | Heldonica', 'SEO — title', true),
  ('destinations-compare', 'seo_description', 'textarea', 'Compare nos destinations slow travel : budget, saison, style et articles publiés. Trouve la destination qui te correspond.', 'SEO — description', true),
  ('destinations-compare', 'seo_og_image', 'text', '${SITE_URL}/og-compare.jpg', 'SEO — image Open Graph', true),
  ('destinations-grece', 'seo_title', 'text', 'Grèce slow travel | Guide Heldonica — Bientôt', 'SEO — title', true),
  ('destinations-grece', 'seo_description', 'textarea', 'Archipels discrets, villages calcaires, tavernes de port. Notre guide Grèce slow travel arrive prochainement — sois notifié en avant-première.', 'SEO — description', true),
  ('destinations-grece', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-idf-fontainebleau', 'seo_title', 'text', 'Fontainebleau en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-idf-fontainebleau', 'seo_description', 'textarea', 'Forêt. Escarpements, escalade en Île-de-France. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-idf-fontainebleau', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-idf-giverny', 'seo_title', 'text', 'Giverny en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-idf-giverny', 'seo_description', 'textarea', 'Monet. Jardins, nymphes en IdF. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-idf-giverny', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-idf', 'seo_title', 'text', 'Île-de-France slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-idf', 'seo_description', 'textarea', 'Paris autrement, Versailles hors saison, Giverny au petit matin. Notre guide Île-de-France pour voyager lentement dans la région la plus visitée du monde.', 'SEO — description', true),
  ('destinations-idf', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-idf-paris', 'seo_title', 'text', 'Paris en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-idf-paris', 'seo_description', 'textarea', 'Capitale. Balades, quartiers en IdF. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-idf-paris', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-idf-versailles', 'seo_title', 'text', 'Versailles en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-idf-versailles', 'seo_description', 'textarea', 'Chateau. Jardins, Grand Canal en IdF. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-idf-versailles', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-lisbonne', 'seo_title', 'text', 'Lisbonne slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-lisbonne', 'seo_description', 'textarea', 'Alfama, Mouraria, miradouros et trams en pente. Lisbonne se ralentit facilement — c''est une ville qui se donne à ceux qui traînent.', 'SEO — description', true),
  ('destinations-lisbonne', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-achadas-da-cruz', 'seo_title', 'text', 'Achadas da Cruz en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-achadas-da-cruz', 'seo_description', 'textarea', 'Le funiculaire. 1000m de chute. Vertige en ⭐ Secret Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-achadas-da-cruz', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-cabo-girao', 'seo_title', 'text', 'Cabo Girão en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-cabo-girao', 'seo_description', 'textarea', 'La plus haute falaise d''Europe. 580 m à pic sur l''océan à Madère. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-cabo-girao', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-camara-de-lobos', 'seo_title', 'text', 'Camara de Lobos en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-camara-de-lobos', 'seo_description', 'textarea', 'Le village de pecheurs. Le plus authentique en ⭐ Hidden Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-camara-de-lobos', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-cote-est', 'seo_title', 'text', 'Côte Est en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-cote-est', 'seo_description', 'textarea', 'Machico, Caniçal, la côte sauvage. L''arrivée en avion à Madère. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-cote-est', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-estreito', 'seo_title', 'text', 'Estreito de Câmara de Lobos en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-estreito', 'seo_description', 'textarea', 'La vallée. Les levadas, les cascades, la forêt à Madère. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-estreito', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-faial', 'seo_title', 'text', 'Faial en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-faial', 'seo_description', 'textarea', 'Le village dans les nuages. Montagne en ⭐ Hidden Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-faial', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-funchal', 'seo_title', 'text', 'Funchal et environs en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-funchal', 'seo_description', 'textarea', 'Guide Funchal : vieille ville, Mercado, téléphérique, restaurants, choses à faire à Madère. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-funchal', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-itineraire-7-jours', 'seo_title', 'text', 'Itinéraire Madère 7 jours | Heldonica', 'SEO — title', true),
  ('destinations-madere-itineraire-7-jours', 'seo_description', 'textarea', 'Itinéraire slow travel Madère sur 7 jours : rythme, points de vue, levadas et adresses locales.', 'SEO — description', true),
  ('destinations-madere-itineraire-7-jours', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-ponta-do-sol', 'seo_title', 'text', 'Ponta do Sol en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-ponta-do-sol', 'seo_description', 'textarea', 'Le bout de l’île. Le plus west. Le moins connu en ⭐ Secret Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-ponta-do-sol', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-portela', 'seo_title', 'text', 'Portela en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-portela', 'seo_description', 'textarea', 'Le village. La vue, le cimetiere, les eucalyptus en ⭐ Secret Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-portela', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-porto-moniz', 'seo_title', 'text', 'Porto Moniz slow travel : piscines naturelles de Madère | Heldonica', 'SEO — title', true),
  ('destinations-madere-porto-moniz', 'seo_description', 'textarea', 'Notre guide pour visiter Porto Moniz à Madère. Baignade dans les piscines de roche volcanique naturelle, vagues atlantiques et conseils slow travel.', 'SEO — description', true),
  ('destinations-madere-porto-moniz', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-ribeiro-frio', 'seo_title', 'text', 'Ribeiro Frio en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-ribeiro-frio', 'seo_description', 'textarea', 'Le centre montagne. Levadas, forêt, altitude à Madère. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-ribeiro-frio', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-santos', 'seo_title', 'text', 'Santos en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-santos', 'seo_description', 'textarea', 'Le petit village. Les tavernes, le vin en ⭐ Hidden Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-santos', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-madere-sao-vicente', 'seo_title', 'text', 'Sao Vicente en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-madere-sao-vicente', 'seo_description', 'textarea', 'Le nord forgotten. Grottes, plage noire, eoliennes en ⭐ Hidden Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-madere-sao-vicente', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-montenegro-kotor', 'seo_title', 'text', 'Kotor avant les croisiéristes — guide slow travel | Heldonica', 'SEO — title', true),
  ('destinations-montenegro-kotor', 'seo_description', 'textarea', 'Notre guide pour découvrir Kotor à son meilleur : lever du soleil sur la baie, remparts vides et vieille ville avant 9h. Conseils terrain pour un slow travel réussi.', 'SEO — description', true),
  ('destinations-montenegro-kotor', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-normandie-cote-albatre', 'seo_title', 'text', 'Côte d Albâtre en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-normandie-cote-albatre', 'seo_description', 'textarea', 'Le village classique. Mais tôt le matin, c''est un autre monde en Normandie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-normandie-cote-albatre', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-normandie-le-havre', 'seo_title', 'text', 'Le Havre et environs en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-normandie-le-havre', 'seo_description', 'textarea', 'Guide Le Havre et environs: architecture Art Deco d Auguste Perret, plages de la Manche, roadtrip en Normandie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-normandie-le-havre', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-normandie', 'seo_title', 'text', 'Normandie slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-normandie', 'seo_description', 'textarea', 'Guide pilier Normandie: Le Havre, Honfleur, Bayeux et les environs. Quand partir, budget réel, où dormir, et choses à faire.', 'SEO — description', true),
  ('destinations-normandie', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-normandie-pays-dauge', 'seo_title', 'text', 'Pays d Auge en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-normandie-pays-dauge', 'seo_description', 'textarea', 'Le portype. Mais hors saison, c''est magic. Lesaufs sur le port en Normandie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-normandie-pays-dauge', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-', 'seo_title', 'text', 'Destinations | Heldonica', 'SEO — title', true),
  ('destinations-', 'seo_description', 'textarea', 'Madère, Roumanie, Sicile et bien d’autres : on te partage nos destinations authentiques testées sur le terrain, loin des foules. Itinéraires et pépites dénichées.', 'SEO — description', true),
  ('destinations-', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-paris', 'seo_title', 'text', 'Paris slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-paris', 'seo_description', 'textarea', 'Paris et l''Île-de-France se lisent mieux quand on sort des grandes phrases. Un canal, une friche, une rue, et le rythme change.', 'SEO — description', true),
  ('destinations-paris', 'seo_og_image', 'text', 'https://www.heldonica.fr/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-portugal-lisbonne', 'seo_title', 'text', 'Lisbonne en couple : notre itinéraire slow travel | Heldonica', 'SEO — title', true),
  ('destinations-portugal-lisbonne', 'seo_description', 'textarea', 'Prendre le temps à Lisbonne : ruelles de l''Alfama, points de vue secrets (miradouros), fado authentique et pépites dénichées en duo.', 'SEO — description', true),
  ('destinations-portugal-lisbonne', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-portugal', 'seo_title', 'text', 'Portugal slow travel | Guide Heldonica — Madère, Porto, Lisbonne', 'SEO — title', true),
  ('destinations-portugal', 'seo_description', 'textarea', 'Guide Portugal slow travel : Madère, Lisbonne, Porto, Alentejo. Nos adresses testées, budgets réels et itinéraires pour un voyage authentique.', 'SEO — description', true),
  ('destinations-portugal', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-portugal-porto', 'seo_title', 'text', 'Porto en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-portugal-porto', 'seo_description', 'textarea', 'Guide Porto: vin de Porto, Ribeira, Douro en Portugal. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-portugal-porto', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-brasov', 'seo_title', 'text', 'Brașov slow travel : notre carnet de voyage | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-brasov', 'seo_description', 'textarea', 'Nichée au pied des Carpates en Transylvanie, Brașov est la destination slow travel par excellence. Conseils, randonnées douces et ruelles médiévales.', 'SEO — description', true),
  ('destinations-roumanie-brasov', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-bucarest', 'seo_title', 'text', 'Bucarest en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-bucarest', 'seo_description', 'textarea', 'Guide Bucarest: Macro, culture, vie nocturne en Roumanie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-roumanie-bucarest', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-cluj', 'seo_title', 'text', 'Cluj-Napoca slow travel : notre carnet d’adresses | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-cluj', 'seo_description', 'textarea', 'Découvre Cluj-Napoca, le cœur culturel et universitaire de la Transylvanie. Cafés de spécialité, ruelles cachées et ambiance bohème pour un séjour slow travel.', 'SEO — description', true),
  ('destinations-roumanie-cluj', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-itineraire-10-jours', 'seo_title', 'text', 'Roumanie 10 jours : grande traversée slow travel en couple | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-itineraire-10-jours', 'seo_description', 'textarea', 'Itinéraire Roumanie 10 jours testé sur place : Bucarest, Brașov, Sighișoara, Viscri, Cluj, Maramureș. Le circuit complet incluant la région la plus authentique du pays.', 'SEO — description', true),
  ('destinations-roumanie-itineraire-10-jours', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-itineraire-5-jours', 'seo_title', 'text', 'Roumanie 5 jours : itinéraire slow travel focus Transylvanie | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-itineraire-5-jours', 'seo_description', 'textarea', 'Itinéraire Roumanie 5 jours testé sur place : Brașov, Sighișoara, Sibiu, château de Peleș, randonnée dans les Carpates. L''essentiel de la Transylvanie en version concentrée.', 'SEO — description', true),
  ('destinations-roumanie-itineraire-5-jours', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-itineraire-7-jours', 'seo_title', 'text', 'Roumanie 7 jours : itinéraire slow travel en couple | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-itineraire-7-jours', 'seo_description', 'textarea', 'Itinéraire Roumanie 7 jours testé sur place : Bucarest, Sinaia, Brașov, Sighișoara, Viscri, Cluj. Budget, hébergements, pépites et conseils slow travel.', 'SEO — description', true),
  ('destinations-roumanie-itineraire-7-jours', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-sibiu', 'seo_title', 'text', 'Sibiu en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-sibiu', 'seo_description', 'textarea', 'Guide Sibiu: fete, montagne, architecture en Roumanie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-roumanie-sibiu', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-timisoara', 'seo_title', 'text', 'Timisoara en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-timisoara', 'seo_description', 'textarea', 'Ville hongroise. Art Nouveau en Roumanie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-roumanie-timisoara', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-roumanie-transylvanie', 'seo_title', 'text', 'Transylvanie en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-roumanie-transylvanie', 'seo_description', 'textarea', 'Guide Transylvanie: chateaux, legends, villages en Roumanie. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-roumanie-transylvanie', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne-alghero', 'seo_title', 'text', 'Alghero en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sardaigne-alghero', 'seo_description', 'textarea', 'Nord-ouest. Influences catalanes en Sardaigne. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sardaigne-alghero', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne-asinara', 'seo_title', 'text', 'Asinara en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sardaigne-asinara', 'seo_description', 'textarea', 'L ile prison. Ane blanchis, exclusivite en ⭐ Hidden Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sardaigne-asinara', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne-cagliari', 'seo_title', 'text', 'Cagliari en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sardaigne-cagliari', 'seo_description', 'textarea', 'Le sud. Lagune, dunes, sel en Sardaigne. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sardaigne-cagliari', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne-costa-smeralda', 'seo_title', 'text', 'Costa Smeralda en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sardaigne-costa-smeralda', 'seo_description', 'textarea', 'Le nord.millionnaires, plages incredible en Sardaigne. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sardaigne-costa-smeralda', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne-nuoro', 'seo_title', 'text', 'Nuoro en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sardaigne-nuoro', 'seo_description', 'textarea', 'Centre. Montagnes, pasteurs en Sardaigne. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sardaigne-nuoro', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sardaigne', 'seo_title', 'text', 'Sardaigne slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-sardaigne', 'seo_description', 'textarea', 'Guide slow travel Sardaigne : plages sauvages, villages de l''intérieur, agritourisme et adresses dénichées loin des foules. Testé par Heldonica.', 'SEO — description', true),
  ('destinations-sardaigne', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile-catane', 'seo_title', 'text', 'Catane en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sicile-catane', 'seo_description', 'textarea', 'Est. Volcan, baroque en Sicile. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sicile-catane', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile-etoile', 'seo_title', 'text', 'Isole Eoliennes en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sicile-etoile', 'seo_description', 'textarea', 'Volcans, boue en ⭐ Secret Gem. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sicile-etoile', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile', 'seo_title', 'text', 'Sicile slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-sicile', 'seo_description', 'textarea', 'Temples grecs, marchés bruyants, côte sauvage. La Sicile se révèle quand on ralentit — une île où chaque village raconte une civilisation différente.', 'SEO — description', true),
  ('destinations-sicile', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile-palerme', 'seo_title', 'text', 'Palerme en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sicile-palerme', 'seo_description', 'textarea', 'Ouest. Capitale, chaos en Sicile. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sicile-palerme', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile-syracuse', 'seo_title', 'text', 'Syracuse en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sicile-syracuse', 'seo_description', 'textarea', 'Sud-est. Antique, Ortigia en Sicile. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sicile-syracuse', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-sicile-taormine', 'seo_title', 'text', 'Taormine en couple : notre carnet slow travel | Heldonica', 'SEO — title', true),
  ('destinations-sicile-taormine', 'seo_description', 'textarea', 'Est. Theatre grec, vue mer en Sicile. Notre guide slow travel testé en couple : pépites locales, adresses insolites et conseils pratiques.', 'SEO — description', true),
  ('destinations-sicile-taormine', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-suisse', 'seo_title', 'text', 'Suisse slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-suisse', 'seo_description', 'textarea', 'Montagnes, lacs, trains impeccables et détours qui demandent du temps. La Suisse devient juste quand on cesse de la résumer à son prix.', 'SEO — description', true),
  ('destinations-suisse', 'seo_og_image', 'text', 'https://www.heldonica.fr/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-timisoara', 'seo_title', 'text', 'Timișoara slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-timisoara', 'seo_description', 'textarea', 'Timișoara, capitale européenne de la culture 2023 : architecture baroque, scène culturelle vivante et cafés de quartier. Notre guide slow travel.', 'SEO — description', true),
  ('destinations-timisoara', 'seo_og_image', 'text', '${SITE_URL}/og-default.jpg', 'SEO — image Open Graph', true),
  ('destinations-zurich', 'seo_title', 'text', 'Zurich slow travel | Guide Heldonica', 'SEO — title', true),
  ('destinations-zurich', 'seo_description', 'textarea', 'Badi flottantes, brasseries artisanales et vieille ville dense. Zurich se révèle quand on ralentit assez pour la laisser venir.', 'SEO — description', true),
  ('destinations-zurich', 'seo_og_image', 'text', 'https://www.heldonica.fr/og-default.jpg', 'SEO — image Open Graph', true),
  ('expert-hotelier', 'seo_title', 'text', 'Hébergements Slow Travel & Indépendance | Heldonica', 'SEO — title', true),
  ('expert-hotelier', 'seo_description', 'textarea', 'Accompagnement pour hôtels indépendants, maisons d’hôtes et gîtes de charme. Valorisez votre positionnement slow travel, réduisez votre dépendance aux plateformes et fidélisez les couples.', 'SEO — description', true),
  ('expert-hotelier', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('guides-merci', 'seo_title', 'text', 'Merci ! | | Téléchargement en cours', 'SEO — title', true),
  ('guides-merci', 'seo_description', 'textarea', 'Ton guide est en train de partir dans ta boîte mail. En attendant, découvre nos autres ressources.', 'SEO — description', true),
  ('guides-merci', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('guides', 'seo_title', 'text', 'Guides de voyage | Heldonica', 'SEO — title', true),
  ('guides', 'seo_description', 'textarea', 'Nos guides pratiques terrain : pépites dénichées, adresses testées, conseils slow travel. Ce qu''on n''a pas mis sur le blog.', 'SEO — description', true),
  ('guides', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('guides-top-10-pepites-madere', 'seo_title', 'text', 'Guide Top 10 Pépites Madère | Heldonica', 'SEO — title', true),
  ('guides-top-10-pepites-madere', 'seo_description', 'textarea', 'Télécharge notre guide des 10 meilleures adresses testées à Madère. Restaurants, sentiers, spots photo — tout ce qu''on a aimé et qu''on te recommande.', 'SEO — description', true),
  ('guides-top-10-pepites-madere', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('maintenance', 'seo_title', 'text', 'En maintenance | Heldonica', 'SEO — title', true),
  ('maintenance', 'seo_description', 'textarea', 'Heldonica est temporairement en maintenance. Nous revenons tres vite avec de nouvelles pepites.', 'SEO — description', true),
  ('maintenance', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('mentions-legales', 'seo_title', 'text', 'Mentions légales | Heldonica', 'SEO — title', true),
  ('mentions-legales', 'seo_description', 'textarea', 'Informations légales de l''éditeur, de l''hébergeur et conditions d''utilisation du site Heldonica.', 'SEO — description', true),
  ('mentions-legales', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('organisateur', 'seo_title', 'text', 'Organisateur de voyage gratuit | Heldonica', 'SEO — title', true),
  ('organisateur', 'seo_description', 'textarea', 'Planifie ton voyage en ligne : itinéraire étape par étape, budget par poste, checklist de départ. Outil gratuit, sauvegarde locale automatique.', 'SEO — description', true),
  ('organisateur', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('page.tsx', 'seo_title', 'text', 'Heldonica — Slow travel vécu en duo, conçu pour toi', 'SEO — title', true),
  ('page.tsx', 'seo_description', 'textarea', 'Un duo Paris-Madère-Roumanie qui voyage lentement, documente vraiment et partage ce qu''il a vécu — pas ce qu''il a lu ailleurs.', 'SEO — description', true),
  ('page.tsx', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('politique-affiliation', 'seo_title', 'text', 'Programme Partenaires & Affiliation | Heldonica', 'SEO — title', true),
  ('politique-affiliation', 'seo_description', 'textarea', 'Politique d''affiliation Heldonica : comment on sélectionne et utilise les liens partenaires (Booking.com, GetYourGuide, etc.) pour financer le site sans compromettre la qualité des recommandations.', 'SEO — description', true),
  ('politique-affiliation', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('politique-confidentialite', 'seo_title', 'text', 'Politique de confidentialité | Heldonica', 'SEO — title', true),
  ('politique-confidentialite', 'seo_description', 'textarea', 'Politique de confidentialité et traitement des données personnelles du site Heldonica.', 'SEO — description', true),
  ('politique-confidentialite', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('slow-travel', 'seo_title', 'text', 'Slow Travel — Voyager Autrement, Lentement, Authentiquement | Heldonica', 'SEO — title', true),
  ('slow-travel', 'seo_description', 'textarea', 'Qu’est-ce que le slow travel ? On te partage notre approche du voyage lent, écoresponsable et hors des sentiers battus. Destinations, conseils et carnets de route.', 'SEO — description', true),
  ('slow-travel', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('start', 'seo_title', 'text', 'Tous nos liens | Heldonica', 'SEO — title', true),
  ('start', 'seo_description', 'textarea', 'Retrouve tous les liens Heldonica : blog, guides gratuits, travel planning et contact.', 'SEO — description', true),
  ('start', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('temoignages', 'seo_title', 'text', 'Témoignages clients | Heldonica', 'SEO — title', true),
  ('temoignages', 'seo_description', 'textarea', 'Retours de couples accompagnés par Heldonica pour leur voyage slow travel sur mesure.', 'SEO — description', true),
  ('temoignages', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true),
  ('travel-planning', 'seo_title', 'text', 'Travel Planning sur mesure | Heldonica', 'SEO — title', true),
  ('travel-planning', 'seo_description', 'textarea', 'On conçoit ton voyage slow travel sur mesure — itinéraire terrain, hébergements testés et suivi humain. Formules à partir de 250€. Devis gratuit.', 'SEO — description', true),
  ('travel-planning', 'seo_og_image', 'text', '/og-default.jpg', 'SEO — image Open Graph', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
