-- ============================================================================
-- Page Alentejo : contenu piloté par le CMS
-- Date: 2026-08-01 — généré par scripts/generate-alentejo-cms.mjs
--
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
('destinations-alentejo', 'hero_badge', 'text', '✦', 'Badge du hero (testé par)', true),
  ('destinations-alentejo', 'hero_label', 'text', 'Destination Portugal', 'Label du hero', true),
  ('destinations-alentejo', 'hero_title', 'text', 'Alentejo : le slow travel absolu', 'Titre du hero', true),
  ('destinations-alentejo', 'hero_subtitle', 'text', 'au cœur du Portugal', 'Sous-titre du hero', true),
  ('destinations-alentejo', 'hero_description', 'textarea', 'Plaines infinies, vignobles à perte de vue, villages de pierre figés dans le temps. L’Alentejo, c’est le Portugal qu’on cherche quand on veut échapper aux foules.', 'Description du hero', true),
  ('destinations-alentejo', 'intro_label', 'text', '', 'Label d''intro (retour terrain)', true),
  ('destinations-alentejo', 'intro_title', 'text', 'Pourquoi l’Alentejo nous a conquis', 'Titre d''intro', true),
  ('destinations-alentejo', 'intro_1', 'html', '<strong className="text-stone-900">La première fois</strong>, on a traversé l’Alentejo en vitesse, direction l’Algarve. Grosse erreur. On a traversé des siècles d’histoire, des plains qui donnaient le vertige, des villages où le temps semblait s’être arrêté — et on n’y a même pas posé pied.', 'Paragraphe d''intro 1', true),
  ('destinations-alentejo', 'intro_2', 'html', '<strong className="text-stone-900">La deuxième fois</strong>, on a pris 5 jours. Juste l’Alentejo central. Évoramonsaraz, les vignobles de Vidigueira, les routes sans autre voiture à l’horizon. C’est là qu’on a compris : l’Alentejo, c’est le Portugal <em>vraiment</em>.', 'Paragraphe d''intro 2', true),
  ('destinations-alentejo', 'intro_3', 'html', 'Ce qu’on y a trouvé : du bon vin à 3€, des restaurants de village où le patron cooking tout lui-même, des champs de liège à perte de vue, et ce silence qu’on cherche tous sans jamais oser le dire.', 'Paragraphe d''intro 3', true),
  ('destinations-alentejo', 'quick_1_label', 'text', 'Meilleure période', 'En bref 1 — label', true),
  ('destinations-alentejo', 'quick_1_value', 'html', 'Mars–Juin<br /><span className="text-eucalyptus">Sept–Nov</span>', 'En bref 1 — valeur', true),
  ('destinations-alentejo', 'quick_2_label', 'text', 'Durée idéale', 'En bref 2 — label', true),
  ('destinations-alentejo', 'quick_2_value', 'html', '5–7 jours', 'En bref 2 — valeur', true),
  ('destinations-alentejo', 'quick_3_label', 'text', 'Budget/jour', 'En bref 3 — label', true),
  ('destinations-alentejo', 'quick_3_value', 'html', '80–130€', 'En bref 3 — valeur', true),
  ('destinations-alentejo', 'quick_4_label', 'text', 'Langue', 'En bref 4 — label', true),
  ('destinations-alentejo', 'quick_4_value', 'html', 'Portugais<br /><span className="text-eucalyptus">+ français</span>', 'En bref 4 — valeur', true),
  ('destinations-alentejo', 'pepite_1_emoji', 'text', '🏛️', 'Pépite 1 — emoji', true),
  ('destinations-alentejo', 'pepite_1_title', 'text', 'Évora', 'Pépite 1 — titre', true),
  ('destinations-alentejo', 'pepite_1_subtitle', 'text', 'La ville UNESCO à taille humaine', 'Pépite 1 — sous-titre', true),
  ('destinations-alentejo', 'pepite_1_desc', 'textarea', 'Capitale de l’Alentejo, classed UNESCO. On a aimé déambuler dans les ruelles avant 9h, visiter la chapelle des Ossements à la première heure (quasi déserte), et manger une açorda alentejana dans une tasca de la place principale.', 'Pépite 1 — description', true),
  ('destinations-alentejo', 'pepite_1_verdict', 'textarea', '⭐ Verdict Heldonica : À faire le matin, avant les bus de tourists.', 'Pépite 1 — verdict', true),
  ('destinations-alentejo', 'pepite_2_emoji', 'text', '🏰', 'Pépite 2 — emoji', true),
  ('destinations-alentejo', 'pepite_2_title', 'text', 'Monsaraz', 'Pépite 2 — titre', true),
  ('destinations-alentejo', 'pepite_2_subtitle', 'text', 'Le village perché sur la plaine', 'Pépite 2 — sous-titre', true),
  ('destinations-alentejo', 'pepite_2_desc', 'textarea', 'Un des plus beaux villages du Portugal. Ruelles étroites, château en ruine avec vue sur l’Estrémadure espagnole, et ce silence le soir quand les derniers touristes repartent.', 'Pépite 2 — description', true),
  ('destinations-alentejo', 'pepite_2_verdict', 'textarea', '⭐ Verdict Heldonica : Restez y dormir, pas qu’une journée.', 'Pépite 2 — verdict', true),
  ('destinations-alentejo', 'pepite_3_emoji', 'text', '🍷', 'Pépite 3 — emoji', true),
  ('destinations-alentejo', 'pepite_3_title', 'text', 'Rota dos Vinhos', 'Pépite 3 — titre', true),
  ('destinations-alentejo', 'pepite_3_subtitle', 'text', 'La route des vignobles', 'Pépite 3 — sous-titre', true),
  ('destinations-alentejo', 'pepite_3_desc', 'textarea', 'On a fait la rota entre Vidigueira et Redondo. Dégustations dans des quintas familiales, vin à 4€ la bouteille sur place, et des hôtes qui te racontent trois générations de tradition viticole.', 'Pépite 3 — description', true),
  ('destinations-alentejo', 'pepite_3_verdict', 'textarea', '⭐ Verdict Heldonica : Prévoyez un driver ou un copilote.', 'Pépite 3 — verdict', true),
  ('destinations-alentejo', 'pepite_4_emoji', 'text', '🏊', 'Pépite 4 — emoji', true),
  ('destinations-alentejo', 'pepite_4_title', 'text', 'Praia Fluvial de Granja', 'Pépite 4 — titre', true),
  ('destinations-alentejo', 'pepite_4_subtitle', 'text', 'Les plages rivières secrètes', 'Pépite 4 — sous-titre', true),
  ('destinations-alentejo', 'pepite_4_desc', 'textarea', 'L’Alentejo intérieur a des plages fluviales incroyables. On a trouvé notre spot préféré près de Granja — une plage sur la rivière avec des eaux claires, des gens du coin, et aucun touriste.', 'Pépite 4 — description', true),
  ('destinations-alentejo', 'pepite_4_verdict', 'textarea', '⭐ Verdict Heldonica : Demandez aux locaux, ils indiquent les meilleurs spots.', 'Pépite 4 — verdict', true),
  ('destinations-alentejo', 'accom_1_emoji', 'text', '🌿', 'Hébergement 1 — emoji', true),
  ('destinations-alentejo', 'accom_1_title', 'text', 'Montes Alentejanos', 'Hébergement 1 — titre', true),
  ('destinations-alentejo', 'accom_1_desc', 'textarea', 'Pour ceux qui veulent être au milieu de la plain. On a dormi dans un monte rénové près de Monsaraz — oliviers, piscine, silence total.', 'Hébergement 1 — description', true),
  ('destinations-alentejo', 'accom_1_tip', 'textarea', '💡 Notre conseil : bookezminimum 3 nuits, le temps de décompresser.', 'Hébergement 1 — conseil', true),
  ('destinations-alentejo', 'accom_2_emoji', 'text', '🏘️', 'Hébergement 2 — emoji', true),
  ('destinations-alentejo', 'accom_2_title', 'text', 'Hôtel de village', 'Hébergement 2 — titre', true),
  ('destinations-alentejo', 'accom_2_desc', 'textarea', 'À Évora ou à Monsaraz même. Pratique pour explorer à pied, et souvent dans des bâtiments historiques restaurés avec goût.', 'Hébergement 2 — description', true),
  ('destinations-alentejo', 'accom_2_tip', 'textarea', '💡 Notre conseil : privilégiez les establecimientos avec petit-déjeuner inclus.', 'Hébergement 2 — conseil', true),
  ('destinations-alentejo', 'accom_3_emoji', 'text', '🍇', 'Hébergement 3 — emoji', true),
  ('destinations-alentejo', 'accom_3_title', 'text', 'Quintas viticoles', 'Hébergement 3 — titre', true),
  ('destinations-alentejo', 'accom_3_desc', 'textarea', 'Dormir chez le viticulteur, c’est possible. On a testé une quinta près de Vidigueira avec degustation privée incluse dans le prix de la chambre.', 'Hébergement 3 — description', true),
  ('destinations-alentejo', 'accom_3_tip', 'textarea', '💡 Notre conseil : contactez directement pour les meilleurs tarifs.', 'Hébergement 3 — conseil', true),
  ('destinations-alentejo', 'transport_1_emoji', 'text', '🚗', 'Transport 1 — emoji', true),
  ('destinations-alentejo', 'transport_1_title', 'text', 'Location de voiture', 'Transport 1 — titre', true),
  ('destinations-alentejo', 'transport_1_desc', 'html', '<strong>Indispensable.</strong> Les distances sont grandes (Évora → Monsaraz = 1h30), les taxis rares, les bus limités. Louez une petite citadine : les routes sont bonnes, le traffic quasi nul.', 'Transport 1 — description', true),
  ('destinations-alentejo', 'transport_1_tip', 'textarea', '💡 Notre conseil : reservez depuis Lisbonne airport, compter 30-40€/jour.', 'Transport 1 — conseil', true),
  ('destinations-alentejo', 'transport_2_emoji', 'text', '🚌', 'Transport 2 — emoji', true),
  ('destinations-alentejo', 'transport_2_title', 'text', 'Bus régionaux', 'Transport 2 — titre', true),
  ('destinations-alentejo', 'transport_2_desc', 'html', 'Sans voiture, les Rede Expressos relient les grandes villes. Mais pour les villages, c’est compliqué.', 'Transport 2 — description', true),
  ('destinations-alentejo', 'cta_title', 'text', 'Tu veux qu’on conçoive ton séjour dans l’Alentejo sur mesure ?', 'Titre du CTA', true),
  ('destinations-alentejo', 'cta_text', 'textarea', 'On te construit un itinerary basé sur nos séjours réels. Vignobles, villages, plages rivières — selon ton rythme.', 'Texte du CTA', true),
  ('destinations-alentejo', 'faq_1_q', 'text', 'Quand partir dans l''Alentejo pour le slow travel ?', 'FAQ 1 — question', true),
  ('destinations-alentejo', 'faq_1_a', 'textarea', 'Les meilleures périodes sont mars-mai et septembre-novembre. Températures agréables (20-28°C), vignobles en fleur ou vendanges, hors des circuits habituels.', 'FAQ 1 — réponse', true),
  ('destinations-alentejo', 'faq_2_q', 'text', 'Combien de jours pour découvrir l''Alentejo ?', 'FAQ 2 — question', true),
  ('destinations-alentejo', 'faq_2_a', 'textarea', 'Comptez minimum 4-5 jours pour faire Évoramonsaraz. 7-10 jours permettent d''explorer la Rota das Aldeias Históricas et les vignobles du sud.', 'FAQ 2 — réponse', true),
  ('destinations-alentejo', 'faq_3_q', 'text', 'Comment se déplacer dans l''Alentejo ?', 'FAQ 3 — question', true),
  ('destinations-alentejo', 'faq_3_a', 'textarea', 'Location de voiture indispensable. Les distances sont grandes et les transports en commun rares. Les routes sont bonnes, le trafic faible — idéal pour un road trip lent.', 'FAQ 3 — réponse', true),
  ('destinations-alentejo', 'faq_4_q', 'text', 'Budget moyen par jour dans l''Alentejo ?', 'FAQ 4 — question', true),
  ('destinations-alentejo', 'faq_4_a', 'textarea', 'Comptez 70-120€/jour en milieu de gamme (hébergement + repas + activités). L''Alentejo est moins cher que le littoral Algarve.', 'FAQ 4 — réponse', true),
  ('destinations-alentejo', 'article_1_label', 'text', 'Portugal', 'Article lié 1 — catégorie', true),
  ('destinations-alentejo', 'article_1_title', 'text', 'Routard dans l’Alentejo : notre journal de bord', 'Article lié 1 — titre', true),
  ('destinations-alentejo', 'article_1_alt', 'text', 'Vignobles de l’Alentejo', 'Article lié 1 — alt image', true),
  ('destinations-alentejo', 'article_2_label', 'text', 'Découvertes Locales', 'Article lié 2 — catégorie', true),
  ('destinations-alentejo', 'article_2_title', 'text', 'Évora : 48h dans la ville UNESCO', 'Article lié 2 — titre', true),
  ('destinations-alentejo', 'article_2_alt', 'text', 'Évora', 'Article lié 2 — alt image', true),
  ('destinations-alentejo', 'article_3_label', 'text', 'Food & Lifestyle', 'Article lié 3 — catégorie', true),
  ('destinations-alentejo', 'article_3_title', 'text', 'Le vin portugais qu’on ramène à chaque fois', 'Article lié 3 — titre', true),
  ('destinations-alentejo', 'article_3_alt', 'text', 'Vins portugais', 'Article lié 3 — alt image', true)
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
