-- Insérer les sous-destinations (version sans emoji pour compatibilité)
INSERT INTO public.cms_sub_destinations (parent_slug, slug, title, teaser, emoji, display_order) VALUES
('madere', 'funchal', 'Funchal', 'La capitale cotiere et ses ruelles fleuries.', '', 0),
('madere', 'porto-moniz', 'Porto Moniz', 'Baignade dans les piscines naturelles de roche volcanique.', '', 1),
('madere', 'cabo-girao', 'Cabo Girao', 'La passerelle de verre sur la falaise cotiere.', '', 2),
('madere', 'camara-de-lobos', 'Camara de Lobos', 'Village typique de pecheurs.', '', 3),
('madere', 'ponta-do-sol', 'Ponta do Sol', 'Le village le plus ensoleille de l ile.', '', 4),
('madere', 'sao-vicente', 'Sao Vicente', 'Grottes volcaniques et vallee verdoyante.', '', 5),
('madere', 'ribeiro-frio', 'Ribeiro Frio', 'Foret de lauriers et point de vue magique.', '', 6),
('madere', 'portela', 'Portela', 'Point de vue spectaculaire sur le rocher de Penha d Aguia.', '', 7),
('madere', 'achadas-da-cruz', 'Achadas da Cruz', 'Le telepherique le plus raide d Europe.', '', 8),
('madere', 'estreito', 'Estreito', 'Vignobles en terrasses du vin de Madere.', '', 9),
('roumanie', 'brasov', 'Brasov', 'Citadelle medievale au coeur de la Transylvanie.', '', 0),
('roumanie', 'bucarest', 'Bucarest', 'Le contraste entre architecture royale et friches industrielles.', '', 1),
('roumanie', 'cluj', 'Cluj-Napoca', 'La capitale vivante et universitaire de la Transylvanie.', '', 2),
('roumanie', 'sibiu', 'Sibiu', 'La ville aux maisons qui ont des yeux.', '', 3),
('roumanie', 'timisoara', 'Timisoara', 'Le berceau de la revolution et capitale culturelle.', '', 4),
('roumanie', 'transylvanie', 'Transylvanie', 'Forets sauvages, chateaux medievaux et routes alpines.', '', 5),
('sicile', 'palerme', 'Palerme', 'Marches de rue animes et joyaux arabo-normands.', '', 0),
('sicile', 'catane', 'Catane', 'La cite baroque au pied de l Etna.', '', 1),
('sicile', 'syracuse', 'Syracuse', 'L ile d Ortygie et vestiges grecs legendaires.', '', 2),
('sicile', 'taormine', 'Taormine', 'Le theatre antique face a la mer ionienne.', '', 3),
('sardaigne', 'cagliari', 'Cagliari', 'Bastions de pierre, flamants roses et lagunes.', '', 0),
('sardaigne', 'alghero', 'Alghero', 'La cite catalane fortifiee face au couchant.', '', 1),
('sardaigne', 'costa-smeralda', 'Costa Smeralda', 'Eaux turquoises et criques de granit sculptees.', '', 2),
('sardaigne', 'nuoro', 'Nuoro', 'Le coeur sauvage et traditionnel de la Barbagia.', '', 3),
('portugal', 'lisbonne', 'Lisbonne', 'Collines pavees, fado envoutant et pasteis de nata.', '', 0),
('portugal', 'porto', 'Porto', 'Caves de porto, pont Dom Luis et vieux quartiers cotiers.', '', 1),
('colombie', 'bogota', 'Bogota', 'Cite andine perchee a 2600 metres d altitude.', '', 0),
('colombie', 'medellin', 'Medellin', 'La ville de l eternel printemps et de la transformation.', '', 1),
('colombie', 'cali', 'Cali', 'Capitale mondiale de la salsa et joie de vivre.', '', 2),
('colombie', 'cartago', 'Cartago', 'Heritage colonial au coeur de la region du cafe.', '', 3),
('normandie', 'cote-albatre', 'Cote d Albatre', 'Falaises de craie blanche spectaculaires et galets.', '', 0),
('normandie', 'le-havre', 'Le Havre', 'Architecture moderne classee UNESCO en bord de mer.', '', 1),
('normandie', 'pays-dauge', 'Pays d Auge', 'Manoirs a colombages, vergers et cidre de terroir.', '', 2)
ON CONFLICT (parent_slug, slug) DO UPDATE SET 
  title = EXCLUDED.title,
  teaser = EXCLUDED.teaser,
  display_order = EXCLUDED.display_order;
