-- ============================================================================
-- Pages itinéraires Roumanie : contenu piloté par le CMS (cms_editable_zones)
-- Date: 2026-08-01 — généré par scripts/generate-itineraries-cms.mjs
--
-- Idempotente : ON CONFLICT (page, zone_key) DO UPDATE.

-- ─── destinations-roumanie-itineraire-5-jours ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
  ('destinations-roumanie-itineraire-5-jours', 'hero_badge', 'text', 'Roumanie — Itinéraire 5 jours', 'Badge du hero'),
  ('destinations-roumanie-itineraire-5-jours', 'hero_title', 'text', 'Roumanie 5 jours : focus Transylvanie', 'Titre du hero'),
  ('destinations-roumanie-itineraire-5-jours', 'hero_description', 'textarea', 'L''essence de la Roumanie en version concentrée : Brașov, Sinaia, Sighișoara, Sibiu — et les Carpates au milieu.', 'Description du hero'),
  ('destinations-roumanie-itineraire-5-jours', 'chip_1', 'text', '2 visites', 'Badge 1'),
  ('destinations-roumanie-itineraire-5-jours', 'chip_2', 'text', 'Septembre 2024', 'Badge 2'),
  ('destinations-roumanie-itineraire-5-jours', 'blurb', 'html', 'Ce circuit 5 jours reprend le meilleur de la Transylvanie sans les longs transferts. Idéal pour un premier contact avec la Roumanie ou un week-end prolongé. <strong>Budget réel : 850 € pour deux, vols inclus.</strong>', 'Blurb « Testé par Heldonica »'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_title', 'text', 'Brașov — Installation et vieille ville', 'Jour 1 — titre'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_location', 'text', 'Brașov', 'Jour 1 — lieu'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_activity', 'textarea', 'Arrivée, vieille ville, rue Republicii, place du Conseil', 'Jour 1 — activité'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_pepite', 'textarea', 'La terrasse du Ceai la Metrou — salon de thé caché sous les arcades, thé maison et vue sur la place', 'Jour 1 — pépite'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_accommodation', 'textarea', 'Hotel Belvedere — 3*, vue citadelle, 50 €/nuit', 'Jour 1 — hébergement'),
  ('destinations-roumanie-itineraire-5-jours', 'day_1_detail', 'textarea', 'On pose les bases à Brașov, la plus belle porte d''entrée de la Transylvanie. La vieille ville se découvre à pied en une après-midi : la rue Republicii, piétonne et bordée d''arcades, la place du Conseil avec ses bâtiments pastel, et la première terrasse pour un café en observant le rythme local. Pas de précipitation — on s''imprègne.', 'Jour 1 — détail'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_title', 'text', 'Château de Peleș et randonnée dans les Carpates', 'Jour 2 — titre'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_location', 'text', 'Sinaia', 'Jour 2 — lieu'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_activity', 'textarea', 'Château de Peleș, forêt des Carpates, randonnée légère', 'Jour 2 — activité'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_pepite', 'textarea', 'Le sentier Sinaia-Cota 1400 — 2h de montée douce à travers la forêt, vue panoramique sur toute la vallée', 'Jour 2 — pépite'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_accommodation', 'textarea', 'Hotel Sinaia — 4*, vue montagne, 70 €/nuit', 'Jour 2 — hébergement'),
  ('destinations-roumanie-itineraire-5-jours', 'day_2_detail', 'textarea', 'À 40 minutes de Brașov, Sinaia est le joyau des Carpates. Le château de Peleș mérite qu''on arrive à l''ouverture — les salles sont plus impressionnantes sans la foule. L''après-midi, on prend un sentier dans la forêt au-dessus de la ville. Les Carpates ont cette capacité à te faire oublier le temps. On redescend fatigué mais apaisé.', 'Jour 2 — détail'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_title', 'text', 'Sighișoara — La citadelle médiévale', 'Jour 3 — titre'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_location', 'text', 'Sighișoara', 'Jour 3 — lieu'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_activity', 'textarea', 'Tour de l''Horloge, escalier couvert, citadelle', 'Jour 3 — activité'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_pepite', 'textarea', 'Restaurant din Turn — dîner dans une tour du 14e siècle, cuisine transylvanienne, 25 € pour deux', 'Jour 3 — pépite'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_accommodation', 'textarea', 'Hotel Sighișoara — 3*, intra-muros, 45 €/nuit', 'Jour 3 — hébergement'),
  ('destinations-roumanie-itineraire-5-jours', 'day_3_detail', 'textarea', 'Sighișoara est un arrêt obligé, et on comprend pourquoi dès qu''on franchit la tour de l''Horloge. La citadelle est vivante, habitée, pas un décor pour touristes. On flâne dans les ruelles pavées, on monte les marches couvertes jusqu''au sommet, et le soir venu, on s''installe au din Turn pour un dîner qui restera dans les mémoires.', 'Jour 3 — détail'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_title', 'text', 'Sibiu — Ambiance saxonne et culture', 'Jour 4 — titre'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_location', 'text', 'Sibiu', 'Jour 4 — lieu'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_activity', 'textarea', 'Grande place, pont des Mensonges, musée ASTRA', 'Jour 4 — activité'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_pepite', 'textarea', 'Le musée ASTRA en plein air — 30 hectares de vie rurale roumaine reconstituée, 5 €, prévois 3h', 'Jour 4 — pépite'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_accommodation', 'textarea', 'Hotel Sibiul — 3*, vieille ville, 50 €/nuit', 'Jour 4 — hébergement'),
  ('destinations-roumanie-itineraire-5-jours', 'day_4_detail', 'textarea', 'Sibiu, ancienne capitale européenne de la culture, a gardé un charme saxon irrésistible. La Grande Place est l''une des plus belles d''Europe de l''Est. Le pont des Mensonges offre une vue parfaite sur la ville basse. L''après-midi au musée ASTRA est une plongée fascinante dans la Roumanie rurale — moulins, églises en bois, fermes reconstituées. Un musée à ciel ouvert unique.', 'Jour 4 — détail'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_title', 'text', 'Retour à Brașov et dernière flânerie', 'Jour 5 — titre'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_location', 'text', 'Brașov', 'Jour 5 — lieu'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_activity', 'textarea', 'Petit déjeuner tardif, dernier tour, départ', 'Jour 5 — activité'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_pepite', 'textarea', 'Boulangerie La Pâine — meilleur cozonac de la ville, à prendre pour la route', 'Jour 5 — pépite'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_accommodation', 'textarea', '', 'Jour 5 — hébergement'),
  ('destinations-roumanie-itineraire-5-jours', 'day_5_detail', 'textarea', 'Dernière matinée à Brașov. On prend le temps : petit déjeuner à la boulangerie La Pâine, dernier tour dans la vieille ville pour acheter un souvenir qui a du sens, et on prend la route vers l''aéroport de Sibiu ou Bucarest. Cinq jours suffisent pour tomber amoureux de la Transylvanie — et pour commencer à planifier le prochain voyage, plus long.', 'Jour 5 — détail')
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();

-- ─── destinations-roumanie-itineraire-7-jours ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
  ('destinations-roumanie-itineraire-7-jours', 'hero_badge', 'text', 'Roumanie — Itinéraire 7 jours', 'Badge du hero'),
  ('destinations-roumanie-itineraire-7-jours', 'hero_title', 'text', 'Roumanie 7 jours : itinéraire slow travel en couple', 'Titre du hero'),
  ('destinations-roumanie-itineraire-7-jours', 'hero_description', 'textarea', 'Bucarest, Sinaia, Brașov, Sighișoara, Viscri, Cluj — le circuit Transylvanie qu''on a testé, ajusté, et qu''on referait sans hésiter.', 'Description du hero'),
  ('destinations-roumanie-itineraire-7-jours', 'chip_1', 'text', '2 visites', 'Badge 1'),
  ('destinations-roumanie-itineraire-7-jours', 'chip_2', 'text', 'Septembre 2024', 'Badge 2'),
  ('destinations-roumanie-itineraire-7-jours', 'chip_3', 'text', 'Automne doré', 'Badge 3'),
  ('destinations-roumanie-itineraire-7-jours', 'blurb', 'html', 'On a testé cet itinéraire en septembre 2024, en plein automne doré. Les températures étaient douces (18-25°C), les couleurs incroyables et les sites nettement moins fréquentés qu''en juillet-août. Chaque étape a été vérifiée, chaque adresse testée — on ne recommande que ce qu''on a vraiment expérimenté. <strong>Budget réel : 1 150 € pour deux, tout compris.</strong>', 'Blurb « Testé par Heldonica »'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_title', 'text', 'Bucarest — Premier contact', 'Jour 1 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_from', 'text', 'Arrivée à l''aéroport Otopeni', 'Jour 1 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_location', 'text', 'Bucarest', 'Jour 1 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_activity', 'textarea', 'Installation dans le quartier Floreasca, découverte du quartier, premier repas roumain', 'Jour 1 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_pepite', 'textarea', 'Restaurant fără Zahăr — cantine locale dans Floreasca, cuisine maison, 12 € pour deux', 'Jour 1 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_accommodation', 'textarea', 'Hotel Cismigiu — 3*, quartier centre, 55 €/nuit', 'Jour 1 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_1_detail', 'textarea', 'On pose les valises dans le quartier Floreasca, loin du bruit du centre. C''est là qu''on trouve les meilleures adresses locales — des cantines où les avocats du coin mangent à midi, des petits parcs où personne ne se prend en photo. Premier dîner : sarmale (choux farcis) et mămăligă (polenta), arrosés de vin de Murfatlar. On rentre tôt, demain la route commence.', 'Jour 1 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_title', 'text', 'Bucarest → Sinaia — Les Carpates', 'Jour 2 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_from', 'text', 'Bucarest (1h30 de route)', 'Jour 2 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_location', 'text', 'Sinaia', 'Jour 2 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_activity', 'textarea', 'Château de Peleș, forêt des Carpates', 'Jour 2 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_pepite', 'textarea', 'Le château de Peleș — arrive à l''ouverture (9h15), tu évites 90 % des groupes', 'Jour 2 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_accommodation', 'textarea', 'Hotel Sinaia — 4*, vue montagne, 70 €/nuit', 'Jour 2 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_2_detail', 'textarea', 'La route Bucarest-Sinaia est une mise en jambe parfaite. Les plaines cèdent progressivement la place aux collines, puis aux Carpates qui surgissent sans prévenir. Le château de Peleș est le premier choc visuel du voyage — un concentré d''architecture néo-Renaissance perché dans la forêt. L''après-midi, on marche dans les bois au-dessus de Sinaia. L''air change, le rythme aussi. On comprend déjà pourquoi on vient ici.', 'Jour 2 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_title', 'text', 'Sinaia → Brașov — La perle transylvanienne', 'Jour 3 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_from', 'text', 'Sinaia (40 min de route)', 'Jour 3 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_location', 'text', 'Brașov', 'Jour 3 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_activity', 'textarea', 'Vieille ville, rue Republicii, tramway nostalgique', 'Jour 3 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_pepite', 'textarea', 'Le tramway 102 jusqu''à la gare de Brașov — un voyage dans le temps pour 0.50 €', 'Jour 3 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_accommodation', 'textarea', 'Hotel Belvedere — 3*, vue sur la citadelle, 50 €/nuit', 'Jour 3 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_3_detail', 'textarea', 'Brașov est la plus belle ville de Transylvanie, point barre. La place du Conseil (Piața Sfatului) est entourée de bâtiments pastel qui n''ont pas besoin de filtre. La rue Republicii — piétonne, bordée d''arcades — est faite pour flâner sans but. On monte jusqu''à la forteresse pour la vue, mais le vrai moment, c''est le tramway 102 : une vieille rame qui traverse la ville avec un bruit de ferraille réconfortant. Soirée dans un restaurant du vieux Brașov : papanași (beignets au fromage blanc et crème) en dessert. Indispensable.', 'Jour 3 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_title', 'text', 'Brașov → Sighișoara — La citadelle habitée', 'Jour 4 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_from', 'text', 'Brașov (1h45 de route)', 'Jour 4 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_location', 'text', 'Sighișoara', 'Jour 4 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_activity', 'textarea', 'Citadelle médiévale, tour de l''Horloge', 'Jour 4 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_pepite', 'textarea', 'Restaurant din Turn — dîner dans une tour médiévale, cuisine transylvanienne revisitée, 25 € pour deux', 'Jour 4 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_accommodation', 'textarea', 'Hotel Sighișoara — 3*, intra-muros, 45 €/nuit', 'Jour 4 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_4_detail', 'textarea', 'Sighișoara est la seule citadelle médiévale d''Europe encore habitée en continu. On y entre par la tour de l''Horloge, on gravit les escaliers couverts, et on débouche sur une place où le temps semble figé. La différence avec Brașov : ici, pas de foule. Les ruelles sont calmes, les chats dorment sur les pavés. Le restaurant din Turn est perché dans une tour — on y mange une mici (saucisses roumaines) en regardant la ville s''illuminer. C''est notre journée préférée du circuit.', 'Jour 4 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_title', 'text', 'Sighișoara → Viscri — Le silence saxon', 'Jour 5 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_from', 'text', 'Sighișoara (45 min de route)', 'Jour 5 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_location', 'text', 'Viscri', 'Jour 5 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_activity', 'textarea', 'Village saxon, église fortifiée UNESCO, Fondation Charles', 'Jour 5 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_pepite', 'textarea', 'Chez Elena — déjeuner chez l''habitant dans sa cour : soupe, pain cuit au feu de bois, 8 €', 'Jour 5 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_accommodation', 'textarea', 'Guesthouse Viscri — chez l''habitant, 35 €/nuit', 'Jour 5 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_5_detail', 'textarea', 'Viscri est ce qui reste de la Roumanie d''avant. Un village saxon où les rues sont en terre battue, où les charrettes croisent les vélos, où le seul bruit vient des cloches des moutons. L''église fortifiée classée UNESCO domine le village. La Fondation Charles (le prince Charles a une maison ici) a aidé à restaurer plusieurs bâtiments, mais l''esprit reste celui d''un village qui vit pour lui-même, pas pour les touristes. On déjeune chez Elena, dans sa cour, assis sur un banc en bois. On repart en comprenant pourquoi on voyage vraiment.', 'Jour 5 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_title', 'text', 'Viscri → Cluj-Napoca — L''effervescence', 'Jour 6 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_from', 'text', 'Viscri (2h45 de route)', 'Jour 6 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_location', 'text', 'Cluj-Napoca', 'Jour 6 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_activity', 'textarea', 'Ville universitaire, scène culturelle, bars alternatifs', 'Jour 6 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_pepite', 'textarea', 'La muzica până la capăt — librairie-café alternative au sous-sol, rue Memorandumului', 'Jour 6 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_accommodation', 'textarea', 'Hotel Deja Vu — 3*, quartier centre, 55 €/nuit', 'Jour 6 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_6_detail', 'textarea', 'Cluj, c''est l''autre Roumanie. Étudiante, connectée, tournée vers l''avenir. Le contraste avec Viscri est brutal : on passe du silence absolu aux terrasses bondées de l''avenue Eroilor. La vie culturelle est bouillonnante — théâtre alternatif, galeries d''art contemporain, bars qui ferment à 4h du matin. On flâne dans le quartier Mărăști, on boit un café chez Laika, on dîne dans un bistro hongrois. Cluj est un rappel que la Roumanie ne se réduit pas à ses cartes postales médiévales.', 'Jour 6 — détail'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_title', 'text', 'Cluj-Napoca → Départ — La dernière gorgée', 'Jour 7 — titre'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_from', 'text', 'Cluj (aéroport)', 'Jour 7 — provenance'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_location', 'text', 'Cluj-Napoca', 'Jour 7 — lieu'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_activity', 'textarea', 'Marché Piața Unirii, café Laika, dernier pătrat de cozonac', 'Jour 7 — activité'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_pepite', 'textarea', 'Café Laika — torréfaction locale, pet-friendly, meilleur flat white de Roumanie', 'Jour 7 — pépite'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_accommodation', 'textarea', '', 'Jour 7 — hébergement'),
  ('destinations-roumanie-itineraire-7-jours', 'day_7_detail', 'textarea', 'Dernier matin à Cluj. On traîne au marché Piața Unirii, on achète un dernier cozonac (brioche à la noix), on boit un café à Laika en faisant le bilan. Sept jours qui passent trop vite — c''est toujours le signe d''un bon voyage. Le vol retour depuis Cluj est direct vers plusieurs villes européennes. Dans l''avion, on commence déjà à rêver au prochain retour. Parce qu''on reviendra — la Roumanie a cette capacité à retenir ceux qui prennent le temps de la connaître.', 'Jour 7 — détail')
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();

-- ─── destinations-roumanie-itineraire-10-jours ────────────────────────────────────────────────────────
INSERT INTO public.cms_editable_zones (page, zone_key, zone_type, value, label, is_active)
VALUES
  ('destinations-roumanie-itineraire-10-jours', 'hero_badge', 'text', 'Roumanie — Itinéraire 10 jours', 'Badge du hero'),
  ('destinations-roumanie-itineraire-10-jours', 'hero_title', 'text', 'Roumanie 10 jours : grande traversée slow travel', 'Titre du hero'),
  ('destinations-roumanie-itineraire-10-jours', 'hero_description', 'textarea', 'Du delta urbain de Bucarest au Maramureș profond — la Roumanie dans toute sa diversité, à un rythme qui laisse place à l''imprévu.', 'Description du hero'),
  ('destinations-roumanie-itineraire-10-jours', 'chip_1', 'text', '2 visites', 'Badge 1'),
  ('destinations-roumanie-itineraire-10-jours', 'chip_2', 'text', 'Septembre 2024', 'Badge 2'),
  ('destinations-roumanie-itineraire-10-jours', 'chip_3', 'text', 'Automne doré', 'Badge 3'),
  ('destinations-roumanie-itineraire-10-jours', 'blurb', 'html', 'Cet itinéraire est le plus complet qu''on ait testé. Les 3 jours supplémentaires dans le Maramureș font toute la différence — c''est là que la Roumanie révèle son âme la plus authentique. <strong>Budget réel : 1 600 € pour deux, tout compris.</strong>', 'Blurb « Testé par Heldonica »'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_title', 'text', 'Bucarest — Premier contact', 'Jour 1 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_location', 'text', 'Bucarest', 'Jour 1 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_activity', 'textarea', 'Installation Floreasca, premier repas roumain', 'Jour 1 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_pepite', 'textarea', 'Restaurant fără Zahăr — cantine locale dans Floreasca, 12 € pour deux', 'Jour 1 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_accommodation', 'textarea', 'Hotel Cismigiu — 3*, centre, 55 €/nuit', 'Jour 1 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_1_detail', 'textarea', 'On pose les valises dans le quartier Floreasca, loin du bruit du centre. C''est là qu''on trouve les meilleures adresses locales — des cantines où les avocats du coin mangent à midi, des petits parcs où personne ne se prend en photo. Premier dîner : sarmale (choux farcis) et mămăligă (polenta), arrosés de vin de Murfatlar. On rentre tôt, demain la route commence.', 'Jour 1 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_title', 'text', 'Bucarest → Sinaia — Les Carpates', 'Jour 2 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_location', 'text', 'Sinaia', 'Jour 2 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_activity', 'textarea', 'Château de Peleș, forêt des Carpates', 'Jour 2 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_pepite', 'textarea', 'Le château de Peleș — arrive à l''ouverture (9h15), tu évites 90 % des groupes', 'Jour 2 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_accommodation', 'textarea', 'Hotel Sinaia — 4*, vue montagne, 70 €/nuit', 'Jour 2 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_2_detail', 'textarea', 'La route Bucarest-Sinaia est une mise en jambe parfaite. Les plaines cèdent progressivement la place aux collines, puis aux Carpates qui surgissent sans prévenir. Le château de Peleș est le premier choc visuel du voyage — un concentré d''architecture néo-Renaissance perché dans la forêt. L''après-midi, on marche dans les bois au-dessus de Sinaia.', 'Jour 2 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_title', 'text', 'Sinaia → Brașov — La perle transylvanienne', 'Jour 3 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_location', 'text', 'Brașov', 'Jour 3 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_activity', 'textarea', 'Vieille ville, rue Republicii, tramway nostalgique', 'Jour 3 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_pepite', 'textarea', 'Le tramway 102 jusqu''à la gare de Brașov — un voyage dans le temps pour 0.50 €', 'Jour 3 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_accommodation', 'textarea', 'Hotel Belvedere — 3*, vue citadelle, 50 €/nuit', 'Jour 3 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_3_detail', 'textarea', 'Brașov est la plus belle ville de Transylvanie. La place du Conseil (Piața Sfatului) est entourée de bâtiments pastel. La rue Republicii — piétonne, bordée d''arcades — est faite pour flâner sans but. On monte jusqu''à la forteresse pour la vue, mais le vrai moment, c''est le tramway 102 : une vieille rame qui traverse la ville avec un bruit de ferraille réconfortant.', 'Jour 3 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_title', 'text', 'Brașov → Sighișoara — La citadelle habitée', 'Jour 4 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_location', 'text', 'Sighișoara', 'Jour 4 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_activity', 'textarea', 'Citadelle médiévale, tour de l''Horloge', 'Jour 4 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_pepite', 'textarea', 'Restaurant din Turn — dîner dans une tour médiévale, cuisine transylvanienne revisitée, 25 € pour deux', 'Jour 4 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_accommodation', 'textarea', 'Hotel Sighișoara — 3*, intra-muros, 45 €/nuit', 'Jour 4 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_4_detail', 'textarea', 'Sighișoara est la seule citadelle médiévale d''Europe encore habitée en continu. On y entre par la tour de l''Horloge, on gravit les escaliers couverts, et on débouche sur une place où le temps semble figé. Le restaurant din Turn est perché dans une tour — on y mange une mici en regardant la ville s''illuminer.', 'Jour 4 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_title', 'text', 'Sighișoara → Viscri — Le silence saxon', 'Jour 5 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_location', 'text', 'Viscri', 'Jour 5 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_activity', 'textarea', 'Village saxon, église fortifiée UNESCO', 'Jour 5 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_pepite', 'textarea', 'Chez Elena — déjeuner chez l''habitant dans sa cour : soupe, pain cuit au feu de bois, 8 €', 'Jour 5 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_accommodation', 'textarea', 'Guesthouse Viscri — chez l''habitant, 35 €/nuit', 'Jour 5 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_5_detail', 'textarea', 'Viscri est ce qui reste de la Roumanie d''avant. Un village saxon où les rues sont en terre battue, où les charrettes croisent les vélos, où le seul bruit vient des cloches des moutons. La Fondation Charles a aidé à restaurer plusieurs bâtiments. On déjeune chez Elena, dans sa cour, assis sur un banc en bois.', 'Jour 5 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_title', 'text', 'Viscri → Cluj-Napoca — L''effervescence', 'Jour 6 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_location', 'text', 'Cluj-Napoca', 'Jour 6 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_activity', 'textarea', 'Arrivée, premiers pas en ville', 'Jour 6 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_pepite', 'textarea', 'La muzica până la capăt — librairie-café alternative au sous-sol, rue Memorandumului', 'Jour 6 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_accommodation', 'textarea', 'Hotel Deja Vu — 3*, centre, 55 €/nuit', 'Jour 6 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_6_detail', 'textarea', 'Cluj, c''est l''autre Roumanie. Étudiante, connectée, tournée vers l''avenir. On flâne dans le quartier Mărăști, on boit un café chez Laika, on dîne dans un bistro hongrois. Cluj est un rappel que la Roumanie ne se réduit pas à ses cartes postales médiévales.', 'Jour 6 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_title', 'text', 'Cluj — Journée culturelle', 'Jour 7 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_location', 'text', 'Cluj-Napoca', 'Jour 7 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_activity', 'textarea', 'Musée ethnographique Romulus Vuia, marché Piața Unirii, quartier Mănăștur', 'Jour 7 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_pepite', 'textarea', 'Musée ethnographique Romulus Vuia — village roumain reconstitué en plein air, 4 €, prévois 2h', 'Jour 7 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_accommodation', 'textarea', 'Hotel Deja Vu — 3*, centre, 55 €/nuit', 'Jour 7 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_7_detail', 'textarea', 'Une journée entière pour explorer Cluj en profondeur. Le musée Romulus Vuia est un bijou méconnu : des maisons paysannes, églises en bois et moulins reconstitués sur 15 hectares en pleine ville. L''après-midi, on traîne au marché Piața Unirii — fruits séchés, fromages de Sibiu, miel de Maramureș. Le quartier Mănăștur, bohème et alternatif, mérite le détour pour ses fresques murales et ses cafés de rue.', 'Jour 7 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_title', 'text', 'Cluj → Maramureș — L''âme de la Roumanie', 'Jour 8 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_location', 'text', 'Maramureș', 'Jour 8 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_activity', 'textarea', 'Route vers le nord, premiers villages en bois', 'Jour 8 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_pepite', 'textarea', 'Le cimetière joyeux de Săpânța — tombes colorées racontant la vie des défunts avec humour, 2 €, unique au monde', 'Jour 8 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_accommodation', 'textarea', 'Guesthouse Maramureș — chez l''habitant, 30 €/nuit', 'Jour 8 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_8_detail', 'textarea', 'La route Cluj-Maramureș traverse des collines qui ressemblent à un tableau. On arrive dans la région la plus authentique de Roumanie — celle que les touristes effleurent sans jamais vraiment explorer. Les villages en bois aux toits de bardeaux, les églises aux flèches élancées, les charrettes qui règnent encore sur les routes. L''après-midi, on visite le cimetière joyeux de Săpânța — une expérience qui défie toutes les attentes. Des tombes bleues, des épitaphes drôles, une leçon de vie.', 'Jour 8 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_title', 'text', 'Maramureș — Immersion totale', 'Jour 9 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_location', 'text', 'Maramureș', 'Jour 9 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_activity', 'textarea', 'Marché paysan du dimanche, villages de bois, églises UNESCO', 'Jour 9 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_pepite', 'textarea', 'Le marché de Sighetu Marmației — producteurs locaux, fromage de burduf, slănină fumée, tout goûter sans retenue', 'Jour 9 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_accommodation', 'textarea', 'Guesthouse Maramureș — chez l''habitant, 30 €/nuit', 'Jour 9 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_9_detail', 'textarea', 'Le Maramureș se vit, pas se visite. On commence au marché de Sighetu Marmației — le dimanche matin, c''est l''effervescence. Paysans en costume traditionnel, fromages de brebis affinés sous l''écorce, pains cuits au feu de bois. L''après-midi, on enchaîne les églises en bois classées UNESCO : Bârsana, Ieud, Desești — chacune avec sa flèche qui perce le ciel. Le soir, le dîner chez l''habitant est un moment suspendu. C''est pour ça qu''on voyage jusqu''ici.', 'Jour 9 — détail'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_title', 'text', 'Maramureș → Cluj — Le retour', 'Jour 10 — titre'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_location', 'text', 'Maramureș / Cluj-Napoca', 'Jour 10 — lieu'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_activity', 'textarea', 'Dernier petit déjeuner paysan, route retour Cluj, vol départ', 'Jour 10 — activité'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_pepite', 'textarea', 'Le marché du dimanche matin — achète du miel et de la palincă (eau-de-vie de prune) pour ramener un vrai goût de Roumanie', 'Jour 10 — pépite'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_accommodation', 'textarea', '', 'Jour 10 — hébergement'),
  ('destinations-roumanie-itineraire-10-jours', 'day_10_detail', 'textarea', 'Dernière gorgée de Maramureș. On prend le temps d''un dernier petit déjeuner — pain chaud, crème fraîche, confiture maison. On achète du miel et de la palincă. Puis la route vers Cluj, 2h30 de virages à travers les collines. Dans l''avion, on est fatigués mais comblés. Dix jours qui ont tout donné. Et déjà, on sait qu''on reviendra — il reste tant de Roumanie à découvrir.', 'Jour 10 — détail')
ON CONFLICT (page, zone_key) DO UPDATE
SET value = EXCLUDED.value, zone_type = EXCLUDED.zone_type,
    label = EXCLUDED.label, is_active = true, updated_at = NOW();
